export default [
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/At_the_Sight_of_their_Comrades,_their_Hearts_Grew_Bold',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/72/Heart_grew_bold_icon.png',
        name: 'At the Sight of their Comrades, their Hearts Grew Bold',
        area: 'Friendly Aura',
        effects: '<ul><li>+10 <a target="_blank" href="/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a></li><li>+10 <a target="_blank" href="/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
        duration: '4.0 seconds',
        linger: '2.0 seconds',
        description: 'Emboldens allies in the area of effect, giving bonuses to Fortitude and Will.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Blessed_Was_Wengridh,_Quickest_of_His_Tribe',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/9a/Blessed_was_icon.png',
        name: 'Blessed Was Wengridh, Quickest of His Tribe',
        area: 'Friendly Aura',
        effects: '<ul><li>+1.2 <a target="_blank" href="/wiki/Move_Speed" title="Move Speed">Move Speed</a></li><li>+10 <a target="_blank" href="/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
        duration: '4.0 seconds',
        linger: '2.0 seconds',
        description: 'Increases the movement rate and Reflex of all allies in the area of effect.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Come,_Come_Soft_Winds_of_Death',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/0e/Winds_of_death_icon.png',
        name: 'Come, Come Soft Winds of Death',
        area: 'Foe Aura',
        effects: '<ul><li>-2 <a target="_blank" href="/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> per 3 seconds</li></ul>',
        duration: '4.0 seconds',
        linger: '2.0 seconds',
        description: 'Drains a portion of Endurance from all enemies in the area of effect.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Dull_the_Edge,_Blunt_the_Point',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8e/Dull_the_edge_icon.png',
        name: 'Dull the Edge, Blunt the Point',
        area: 'Foe Aura',
        effects: '<ul><li>-10% <a target="_blank" href="/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>-10% <a target="_blank" href="/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
        duration: '4.0 seconds',
        linger: '2.0 seconds',
        description: 'Reduces Slashing and Piercing damage of enemies in the area of effect.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Thick_Grew_Their_Tongues,_Stumbling_O%27er_Words',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/fb/Tongue_tied_icon.png',
        name: 'Thick Grew Their Tongues, Stumbling O\'er Words',
        area: 'Foe Aura',
        effects: '<ul><li>-10 <a target="_blank" href="/wiki/Concentration" class="mw-redirect" title="Concentration">Concentration</a></li></ul>',
        duration: '4.0 seconds',
        linger: '2.0 seconds',
        description: 'Reduces Concentration of enemies in the area of effect.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Lo,_Their_Endless_Host,_the_Harbingers_Doom',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/07/Endless_host_icon.png',
        name: 'Lo, Their Endless Host, the Harbingers Doom',
        area: 'Foe Aura',
        effects: '<ul><li><a target="_blank" href="/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a></li></ul>',
        duration: '6.0 seconds',
        linger: '3.0 seconds',
        description: 'Generates a field of terror, Frightening enemies in the area of effect.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/One_Dozen_Stood_Against_the_Power_of_the_Saint',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/3e/One_dozen_stood_icon.png',
        name: 'One Dozen Stood Against the Power of the Saint',
        area: 'Friendly Aura',
        effects: '<ul><li>+25 <a target="_blank" href="/wiki/Defense" title="Defense">Defense</a> vs <a target="_blank" href="/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a></li><li>-10 seconds <a target="_blank" href="/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a> duration</li><li>+15 <a target="_blank" href="/wiki/Defense" title="Defense">Defense</a> vs <a target="_blank" href="/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a></li><li>-5 seconds <a target="_blank" href="/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a> duration</li></ul>',
        duration: '6.0 seconds',
        linger: '3.0 seconds',
        description: 'Decreases the duration of and defends against Frightened and Terrified effects for allies in the area of effect.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Rime_and_Frost_Followed_the_Footfalls_of_Karth',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/5c/Rime_and_frost_icon.png',
        name: 'Rime and Frost Followed the Footfalls of Karth',
        area: 'Friendly Aura',
        effects: '<ul><li>Drop Trap: Rime and Frost Trap per 3 seconds</li><li>Trap causes <a target="_blank" href="/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a> for 10 seconds</li></ul>',
        duration: '6.0 seconds',
        linger: '3.0 seconds',
        description: 'Allies leave a hazardous trail of frost wherever they move, Hobbling and causing Freeze damage to enemies.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Sure-Handed_Ila_Nocked_Her_Arrows_with_Speed',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/46/Sure_handed_ila_icon.png',
        name: 'Sure-Handed Ila Nocked Her Arrows with Speed',
        area: 'Friendly Aura',
        effects: '<ul><li>+20% <a target="_blank" href="/wiki/Reload_Speed?action=edit&amp;redlink=1" class="new" title="Reload Speed (page does not exist)">Reload Speed</a></li><li>+20% Ranged <a target="_blank" href="/wiki/Attack_Speed" title="Attack Speed">Attack Speed</a></li></ul>',
        duration: '6.0 seconds',
        linger: '3.0 seconds',
        description: 'Decreases reload time and increases the speed of ranged attacks for all allies.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/The_Fox_from_the_Farmer_Did_Run_and_Leap',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1d/Fox_leap_icon.png',
        name: 'The Fox from the Farmer Did Run and Leap',
        area: 'Foe Aura',
        effects: '<ul><li>-10 <a target="_blank" href="/wiki/Accuracy" title="Accuracy">Accuracy</a> on <a target="_blank" href="/wiki/Disengagement" class="mw-redirect" title="Disengagement">Disengagement</a> attacks</li></ul>',
        duration: '6.0 seconds',
        linger: '3.0 seconds',
        description: 'Reduces Accuracy of Disengagement Attacks for enemies in the area of effect.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Aefyllath_Ues_Mith_Fyr',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/0b/Mith_fyr_icon.png',
        name: 'Aefyllath Ues Mith Fyr',
        area: 'Friendly Aura',
        effects: '<ul><li>+25% <a target="_blank" href="/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
        duration: '8.0 seconds',
        linger: '4.0 seconds',
        description: 'Bestows a Burning effect on all ally weapons.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Seven_Men,_Onto_the_Deck_They_Went',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/2a/Seven_men_icon.png',
        name: 'Seven Men, Onto the Deck They Went',
        area: 'Friendly Aura',
        effects: '<ul><li>+15 <a target="_blank" href="/wiki/Defense" title="Defense">Defense</a> vs <a target="_blank" href="/wiki/Prone" class="mw-redirect" title="Prone">Prone</a> attacks</li><li>+15 <a target="_blank" href="/wiki/Concentration" class="mw-redirect" title="Concentration">Concentration</a></li><li>+10 <a target="_blank" href="/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png" decoding="async" width="18" height="18" /></a></li><li>+10 <a target="_blank" href="/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
        duration: '8.0 seconds',
        linger: '4.0 seconds',
        description: 'Allies in the area of effect gain a bonus to Freeze and Shock Damage Reductions, and a bonus to defense against the Prone affliction.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/The_Dragon_Thrashed,_The_Dragon_Wailed',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/41/Dragon_thrashed_icon.png',
        name: 'The Dragon Thrashed, The Dragon Wailed',
        area: 'Foe Aura',
        effects: '<ul><li>10 <a target="_blank" href="/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage per 3 seconds</li><li>10 <a target="_blank" href="/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a> damage per 3 seconds</li></ul>',
        duration: '8.0 seconds',
        linger: '4.0 seconds',
        description: 'Generates a hazard field causing Burn and Slash damage to enemies in the area of effect.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/The_Silver_Knights%27_Shields_Broke_Both_Arrow_and_Blade',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d4/Silver_shield_icon.png',
        name: 'The Silver Knights\' Shields Broke Both Arrow and Blade',
        area: 'Friendly Aura',
        effects: '<ul><li>+10 <a target="_blank" href="/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a></li></ul>',
        duration: '8.0 seconds',
        linger: '4.0 seconds',
        description: 'Increases the Deflection of allies in the area of effect.',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/Her_Courage_Thick_as_Steel',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/df/Her_courage_thick_as_steel_icon.png',
        name: 'Her Courage Thick as Steel',
        area: 'Friendly Aura',
        effects: '<ul><li>30-pt Damage Shield</li></ul>',
        duration: '10.0 seconds',
        linger: '5.0 seconds',
        description: 'Provides a barrier that soaks up damage against the chanter\'s allies.',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/Old_Siec_Would_Not_Rest_%27til_His_Hunger_Was_Sated',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/84/Old_siec_would_not_rest_icon.png',
        name: 'Old Siec Would Not Rest \'til His Hunger Was Sated',
        area: 'Friendly Aura',
        effects: '<ul><li>15% of <a target="_blank" href="/wiki/Damage" class="mw-redirect" title="Damage">Damage</a> is restored as <a target="_blank" href="/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a></li></ul>',
        duration: '10.0 seconds',
        linger: '5.0 seconds',
        description: 'The chanter\'s allies regain a portion of damage they inflict as Endurance.',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/They_Shielded_Their_Eyes_%27Gainst_the_Fampyr%27s_Gaze',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1e/They_shielded_their_eyes_icon.png',
        name: 'They Shielded Their Eyes \'Gainst the Fampyr\'s Gaze',
        area: 'Friendly Aura',
        effects: '<ul><li>+20 <a target="_blank" href="/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Confused" class="mw-redirect" title="Confused">Confused</a> attacks</li><li>+20 <a target="_blank" href="/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Charmed" class="mw-redirect" title="Charmed">Charmed</a> attacks</li><li>+20 <a target="_blank" href="/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Dominated" class="mw-redirect" title="Dominated">Dominated</a> attacks</li><li>+20 <a target="_blank" href="/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
        duration: '10.0 seconds',
        linger: '5.0 seconds',
        description: 'The chanter\'s allies gain a bonus to their Will defense and to resist Charmed, Confused, Dominated afflictions.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/Mercy_and_Kindness_Followed_Where%27er_She_Walked',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Mercy_and_kindness_icon.png',
        name: 'Mercy and Kindness Followed Where\'er She Walked',
        area: 'Friendly Aura',
        effects: '<ul><li>+100% <a target="_blank" href="/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png" decoding="async" width="16" height="16" /></a> received</li></ul>',
        duration: '12.0 seconds',
        linger: '6.0 seconds',
        description: 'All allies receive more Endurance from healing effects.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/With_All_Your_Strength_Slay_the_Beast',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d2/With_all_your_strength_icon.png',
        name: 'With All Your Strength Slay the Beast',
        area: 'Friendly Aura',
        effects: '<ul><li>+20 <a target="_blank" href="/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Beasts" class="mw-redirect" title="Beasts">Beasts</a></li><li>+30% <a target="_blank" href="/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png" decoding="async" width="18" height="18" /></a> vs <a target="_blank" href="/wiki/Beasts" class="mw-redirect" title="Beasts">Beasts</a></li></ul>',
        duration: '12.0 seconds',
        linger: '6.0 seconds',
        description: 'The chanter increases allies\' Accuracy and Damage against all enemies of the Beast type.',
    },
];
