export default [
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Arkemyr%27s_Dazzling_Lights',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/57/Arkemyrs_dazzling_lights_icon.png',
        name: 'Arkemyr\'s Dazzling Lights',
        speed: 'Average',
        range: '',
        area: '1.25m Radius',
        duration: '12.0 seconds',
        effects: '<ul><li>Foe AoE: -10 <a href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png/revision/latest/scale-to-width-down/18?cb=20170909202632" decoding="async" width="18" height="18" /></a></li><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Dazed" class="mw-redirect" title="Dazed">Dazed</a></li></ul>',
        description: 'Overwhelms anyone in the area of effect with a brilliant and bewildering pyrotechnic display, decreasing their Will and leaving them Dazed.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Chill_Fog',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/b/b0/Chill_fog_icon.png',
        name: 'Chill Fog',
        speed: 'Average',
        range: '',
        area: '2.5m Radius',
        duration: '15.0 seconds',
        effects: '<ul><li>AoE: 12-18 <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png/revision/latest/scale-to-width-down/18?cb=20170909202622" decoding="async" width="18" height="18" /></a> damage</li><li>AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Blinded" class="mw-redirect" title="Blinded">Blinded</a> for 3 seconds</li></ul>',
        description: 'Calls a blindingly white icy fog into existence, inflicting Blindness and Freeze damage over time to any in the area of effect.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Concelhaut%27s_Parasitic_Staff',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/9b/Concelhauts_parasitic_staff_icon.png',
        name: 'Concelhaut\'s Parasitic Staff',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Summon Weapon: <a href="https://pillarsofeternity.fandom.com/wiki/Concelhaut%27s_Parasitic_Quarterstaff" title="Concelhaut&#39;s Parasitic Quarterstaff">Concelhaut\'s Parasitic Quarterstaff</a></li></ul>',
        description: 'Creates a glowing quarterstaff of pure energy for the wizard to wield, granting a bonus chance to hit and giving the wizard Endurance with each successful strike.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Eldritch_Aim',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/4d/Eldritch_aim_icon.png',
        name: 'Eldritch Aim',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '10.0 seconds',
        effects: '<ul><li>Caster: +15 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy">Accuracy</a> for 10.0 sec</li></ul>',
        description: 'Grants the caster otherworldly sight, resulting in preternatural Accuracy for a short period.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Fan_of_Flames',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/46/Fan_of_flames_icon.png',
        name: 'Fan of Flames',
        speed: 'Average',
        range: '',
        area: 'Length: 5.0m 120° Cone',
        duration: '',
        effects: '<ul><li>AoE: 30-42 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235248" decoding="async" width="18" height="18" /></a> damage</li></ul>',
        description: 'Creates a cone of fire in front of the caster, causing Burn damage to anyone in the area of effect.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Fleet_Feet',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/a8/Fleet_feet_icon.png',
        name: 'Fleet Feet',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '30.0 seconds',
        effects: '<ul><li>Caster: +3 <a href="https://pillarsofeternity.fandom.com/wiki/Move_Speed" title="Move Speed">Move Speed</a>, +20 <a href="https://pillarsofeternity.fandom.com/wiki/Defense" title="Defense">Defenses</a> when <a href="https://pillarsofeternity.fandom.com/wiki/Disengaging" class="mw-redirect" title="Disengaging">Disengaging</a> for 30.0 sec</li></ul>',
        description: 'Empowers the target with unnatural speed, increasing their Movement Rate.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Ghost_Blades',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/16/Ghost_blades_icon.png',
        name: 'Ghost Blades',
        speed: 'Average',
        range: '',
        area: 'Length: 5.0m 145° Cone',
        duration: '4.0 seconds',
        effects: '<ul><li>Foe AoE: 20-30 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" class="mw-redirect" title="Pierce">Pierce</a> Damage, <a href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a> for 4.0 sec</li></ul>',
        description: 'Calls a field of unearthly blades into existence, inflicting immediate Pierce damage and a Hobbled affliction on targets in the area of effect.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Jolting_Touch',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/22/Jolting_touch_icon.png',
        name: 'Jolting Touch',
        speed: 'Average',
        range: '',
        area: 'Target + 2 Foe Jump Targets',
        duration: '',
        effects: '<ul><li>Target: 20-35 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" class="mw-redirect" title="Shock">Shock</a> Damage</li><li>Foe Jump Targets (x2): 15-26 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" class="mw-redirect" title="Shock">Shock</a> Damage</li></ul>',
        description: 'A bolt of electricity jumps from the caster\'s fingers to the nearest enemy, and then to the next nearest, causing decreasing amounts of Shock damage.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Kalakoth%27s_Sunless_Grasp',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1f/Kalakoths_sunless_grasp_icon.png',
        name: 'Kalakoth\'s Sunless Grasp',
        speed: 'Average',
        range: '',
        area: '',
        duration: '15.0 seconds',
        effects: '<ul><li>Target: 18-26 <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" class="mw-redirect" title="Freeze">Freeze</a> Damage, -10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy">Accuracy</a> for 15.0 sec</li></ul>',
        description: 'The caster\'s hands become so cold as to freeze what they touch. Does Freeze damage to a target and reduces its Accuracy.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Minoletta%27s_Minor_Missiles',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/41/Minolettas_minor_missiles_icon.png',
        name: 'Minoletta\'s Minor Missiles',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '',
        effects: '<ul><li>Target: 12-21 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" class="mw-redirect" title="Crush">Crush</a> / <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" class="mw-redirect" title="Corrode">Corrode</a> Damage</li></ul>',
        description: 'Summons three spell missiles that batter the target, inflicting Crush or Corrode damage.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Slicken',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/61/Slicken_icon.png',
        name: 'Slicken',
        speed: 'Average',
        range: '10m',
        area: '2.5m Radius',
        duration: '4.0 seconds',
        effects: '<ul><li>AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Prone" class="mw-redirect" title="Prone">Prone</a></li></ul>',
        description: 'Coats the ground in a slick, oil-like substance, inflicting Knockdown on anyone in the area of effect.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Spirit_Shield',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/89/Spirit_shield_icon.png',
        name: 'Spirit Shield',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Caster: +3 <a href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png/revision/latest/scale-to-width-down/16?cb=20171001055953" decoding="async" width="16" height="16" /></a></li><li>Caster: +30 <a href="https://pillarsofeternity.fandom.com/wiki/Concentration" class="mw-redirect" title="Concentration">Concentration</a></li></ul>',
        description: 'Surrounds the caster with a shield of spirit energy, granting an increased Damage Reduction and a Concentration bonus.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Thrust_Of_Tattered_Veils',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/a5/Thrust_of_tattered_veils_icon.png',
        name: 'Thrust Of Tattered Veils',
        speed: 'Fast',
        range: '10m',
        area: '',
        duration: '',
        effects: '<ul><li>Target: 18-35 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235303" decoding="async" width="18" height="18" /></a> damage</li></ul>',
        description: 'A quick strike of Crushing force, dealing little damage but having a high chance to disrupt enemy spellcasters.',
    },
    {
        level: '1',
        link: 'https://pillarsofeternity.fandom.com/wiki/Wizard%27s_Double',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/99/Wizards_double_icon.png',
        name: 'Wizard\'s Double',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '',
        effects: '<ul><li>Caster: +40 <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235317" decoding="async" width="18" height="18" /></a> until <a href="https://pillarsofeternity.fandom.com/wiki/Hit" class="mw-redirect" title="Hit">Hit</a> or <a href="https://pillarsofeternity.fandom.com/wiki/Crit" class="mw-redirect" title="Crit">Critically</a> hit</li></ul>',
        description: 'Creates a duplicate of the caster to distract enemies, granting the caster a high Deflection bonus until he or she is Hit or Crit.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Bewildering_Spectacle',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1d/Bewildering_spectacle_icon.png',
        name: 'Bewildering Spectacle',
        speed: 'Average',
        range: '',
        area: '1.25m Radius',
        duration: '5.0 seconds',
        effects: '<ul><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Confused" class="mw-redirect" title="Confused">Confused</a> for 5.0 sec</li></ul>',
        description: 'Creates a bizarre and perplexing visual distraction, Confusing enemies in the area of effect.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Binding_Web',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/f7/Binding_web_icon.png',
        name: 'Binding Web',
        speed: 'Average',
        range: '',
        area: '2.5m Radius',
        duration: '10.0 seconds',
        effects: '<ul><li>AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Stuck" class="mw-redirect" title="Stuck">Stuck</a> (Web) for 3 seconds</li></ul>',
        description: 'Spins a resilient, viscous web throughout the area of effect, leaving unfortunate victims Stuck inside.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Bulwark_Against_The_Elements',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Bulwark_against_the_elements_icon.png',
        name: 'Bulwark Against The Elements',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '60.0 seconds',
        effects: '<ul><li>Caster: +15 <a href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png/revision/latest/scale-to-width-down/16?cb=20171001055953" decoding="async" width="16" height="16" style="vertical-align: text-top" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235248" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235346" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235258" decoding="async" width="18" height="18" /></a> <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png/revision/latest/scale-to-width-down/18?cb=20170909202622" decoding="async" width="18" height="18" /></a></li></ul>',
        description: 'Creates a mystical shield around the caster, suffusing them with bonuses to Burn, Freeze, Corrode, and Shock Damage Reductions.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Combusting_Wounds',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/b/ba/Combusting_wounds_icon.png',
        name: 'Combusting Wounds',
        speed: 'Average',
        range: '',
        area: '1.25m Radius',
        duration: '20.0 seconds',
        effects: '<ul><li>Foe AoE: 5 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235248" decoding="async" width="18" height="18" /></a> damage over time when dealt damage</li></ul>',
        description: 'Causes enemy wounds in the area of effect to ignite, inflicting additional Burn damage over time each time they are wounded.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Concelhaut%27s_Corrosive_Siphon',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/19/Concelhauts_corrosive_siphon_icon.png',
        name: 'Concelhaut\'s Corrosive Siphon',
        speed: 'Average',
        range: '',
        area: '1.25m Radius',
        duration: '10.0 seconds',
        effects: '<ul><li>Foe AoE: Drains 43.3 <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235258" decoding="async" width="18" height="18" /></a> damage as <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> over time</li></ul>',
        description: 'Eats away at the target\'s spirit, inflicting Corrosive damage and converting that essence into Endurance for the caster.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Concelhaut%27s_Draining_Missiles',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/9d/Concelhauts_draining_missiles_icon.png',
        name: 'Concelhaut\'s Draining Missiles',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '',
        effects: '<ul><li>Target: Drains 12 <a href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage as <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235322" decoding="async" width="16" height="16" /></a></li></ul>',
        description: 'Concelhaut\'s variant of Minoletta\'s Minor Missiles does Raw damage, attacks the target\'s Fortitude, and grants drained Endurance to the caster.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Curse_of_Blackened_Sight',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/73/Curse_of_blackened_sight_icon.png',
        name: 'Curse of Blackened Sight',
        speed: 'Average',
        range: '',
        area: '1.25m Radius',
        duration: '20.0 seconds',
        effects: '<ul><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Blinded" class="mw-redirect" title="Blinded">Blinded</a> for 20.0 sec</li></ul>',
        description: 'Shrouds the targets\' vision in total darkness, Blinding them.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Fetid_Caress',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/02/Fetid_caress_icon.png',
        name: 'Fetid Caress',
        speed: 'Average',
        range: '',
        area: 'Target + 1.25m Radius',
        duration: '8.0 seconds',
        effects: '<ul><li>Target: <a href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a> for 8.0 sec</li><li>AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a> for 6.0 sec</li></ul>',
        description: 'The target becomes Paralyzed, afflicted with boiling pustules of foul-smelling liquid that erupt from their skin, Sickening those nearby.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Infuse_With_Vital_Essence',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/12/Infuse_with_vital_essence_icon.png',
        name: 'Infuse With Vital Essence',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Caster: +50 Max <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a>, +50 Max <a href="https://pillarsofeternity.fandom.com/wiki/Health" class="mw-redirect" title="Health">Health</a> for 45.0 sec</li></ul>',
        description: 'Infuses the caster with vitality, giving them a temporary increase to maximum Endurance and Health.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Merciless_Gaze',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/c/ca/Merciless_gaze_icon.png',
        name: 'Merciless Gaze',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Caster: +15% of <a href="https://pillarsofeternity.fandom.com/wiki/Hit" class="mw-redirect" title="Hit">Hits</a> converted to <a href="https://pillarsofeternity.fandom.com/wiki/Crit" class="mw-redirect" title="Crit">Crits</a> for 45.0 sec</li></ul>',
        description: 'The caster becomes able to see an enemy\'s weaknesses and vulnerabilities as though they were physically tangible, increasing the chance of landing a Critical Hit.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Miasma_of_Dull-Mindedness',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/68/Miasma_of_dull-mindedness_icon.png',
        name: 'Miasma of Dull-Mindedness',
        speed: 'Average',
        range: '',
        area: '1.25m Radius',
        duration: '12.0 seconds',
        effects: '<ul><li>AoE: -6 <a href="https://pillarsofeternity.fandom.com/wiki/Perception" title="Perception">Perception</a>, -6 <a href="https://pillarsofeternity.fandom.com/wiki/Intellect" title="Intellect">Intellect</a>, -6 <a href="https://pillarsofeternity.fandom.com/wiki/Resolve" title="Resolve">Resolve</a> for 12.0 sec</li></ul>',
        description: 'A cloud of heavy fog settles in the minds of those in the area of effect, dulling senses and wits. Inflicts penalties to Perception, Intellect, and Resolve.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Mirrored_Image',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/fa/Mirrored_image_icon.png',
        name: 'Mirrored Image',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '60.0 seconds',
        effects: '<ul><li>Caster: +25 <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235317" decoding="async" width="18" height="18" /></a> until <a href="https://pillarsofeternity.fandom.com/wiki/Hit" class="mw-redirect" title="Hit">Hit</a> or <a href="https://pillarsofeternity.fandom.com/wiki/Crit" class="mw-redirect" title="Crit">Critically</a> hit for 60.0 sec</li></ul>',
        description: 'Creates duplicates of the caster to distract enemies, granting a high Deflection bonus which is reduced with each hit taken.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Necrotic_Lance',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e5/Necrotic_lance_icon.png',
        name: 'Necrotic Lance',
        speed: 'Average',
        range: '',
        area: '',
        duration: '5.0 seconds',
        effects: '<ul><li>Target: 35-45 <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" class="mw-redirect" title="Corrode">Corrode</a> Damage, 26.7 <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" class="mw-redirect" title="Corrode">Corrode</a> Damage over 5.0 sec</li></ul>',
        description: 'Creates a lance of pure necrotic energy, causing Corrode damage instantly and over time.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Ray_of_Fire',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d7/Ray_of_fire_icon.png',
        name: 'Ray of Fire',
        speed: 'Average',
        range: '',
        area: '',
        duration: '10.0 seconds',
        effects: '<ul><li>Target: 9-16 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" class="mw-redirect" title="Burn">Burn</a> Damage per 1.0 sec</li><li>Beam: Applies the same effect as Target</li></ul>',
        description: 'Creates a scorching ray of flame between the caster and the target, inflicting continual Burn damage to the target and anyone caught in the ray.',
    },
    {
        level: '3',
        link: 'https://pillarsofeternity.fandom.com/wiki/Rolling_Flame',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/56/Rolling_flame_icon.png',
        name: 'Rolling Flame',
        speed: 'Average',
        range: '',
        area: 'Length: 30m, bounces up to 3 times',
        duration: '',
        effects: '<ul><li>Target: 20-30 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235248" decoding="async" width="18" height="18" /></a> damage</li><li>On bounce: -50% damage</li></ul>',
        description: 'Creates a rebounding ball of fire, inflicting Burn damage upon anyone in its path.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Arcane_Dampener',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/28/Arcane_dampener_icon.png',
        name: 'Arcane Dampener',
        speed: 'Average',
        range: '',
        area: '2.5m Radius',
        duration: '15.0 seconds',
        effects: '<ul><li>Foe AoE: Beneficial effects suspended</li></ul>',
        description: 'Creates a nullifying field of antagonistic magical energy around the chosen point, suppressing all beneficial effects on enemies in the area of effect.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Arduous_Delay_of_Motion',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Arduous_delay_of_motion_icon.png',
        name: 'Arduous Delay of Motion',
        speed: 'Average',
        range: '',
        area: '1.75m Radius',
        duration: '15.0 seconds',
        effects: '<ul><li>Foe AoE: -30% <a href="https://pillarsofeternity.fandom.com/wiki/Attack_Speed" title="Attack Speed">Attack Speed</a></li><li>Foe AoE: -2 <a href="https://pillarsofeternity.fandom.com/wiki/Move_Speed" title="Move Speed">Move Speed</a></li></ul>',
        description: 'Alters the perception of time for enemies in the area of effect, lowering their Speed and Movement.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Concelhaut%27s_Draining_Touch',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/01/Concelhauts_draining_touch_icon.png',
        name: 'Concelhaut\'s Draining Touch',
        speed: 'Average',
        range: '',
        area: '',
        duration: '20.0 seconds',
        effects: '<ul><li>Target: Drains 30 <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235258" decoding="async" width="18" height="18" /></a> damage as <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235322" decoding="async" width="16" height="16" /></a></li><li>If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a></li></ul>',
        description: 'The caster\'s hand becomes a toxic parasite, causing Corrosive damage to the target, Weakening it, and converting its lifeforce to the caster as Endurance.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Crackling_Bolt',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/11/Crackling_bolt_icon.png',
        name: 'Crackling Bolt',
        speed: 'Fast',
        range: '',
        area: 'Length: 30m, bounces up to 3 times',
        duration: '',
        effects: '<ul><li>Target: 30-50 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235346" decoding="async" width="18" height="18" /></a> damage</li><li>On bounce: -50% damage</li></ul>',
        description: 'Caster becomes a living generator for a powerful bolt of electricity that streaks out in a straight line and bounces off of walls, harming anything caught in its path.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Deleterious_Alacrity_of_Motion',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/66/Deleterious_alacrity_of_motion_icon.png',
        name: 'Deleterious Alacrity of Motion',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '30.0 seconds',
        effects: '<ul><li>Caster: +50% <a href="https://pillarsofeternity.fandom.com/wiki/Attack_Speed" title="Attack Speed">Attack Speed</a> for 30.0 sec, 11 <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> over 30.0 sec, +2 <a href="https://pillarsofeternity.fandom.com/wiki/Move_Speed" title="Move Speed">Move Speed</a> for 30.0 sec</li></ul>',
        description: 'Caster draws upon his or her life force to gain an increase to Speed and Movement while draining his or her own Endurance.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Expose_Vulnerabilities',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/ae/Expose_vulnerabilities_icon.png',
        name: 'Expose Vulnerabilities',
        speed: 'Average',
        range: '',
        area: '2.5m Radius',
        duration: '20.0 seconds',
        effects: '<ul><li>Foe AoE: -5 <a href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction">Damage Reduction</a>, -10 <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a>, -10 <a href="https://pillarsofeternity.fandom.com/wiki/Concentration" class="mw-redirect" title="Concentration">Concentration</a> for 20.0 sec</li></ul>',
        description: 'Bares the enemies\' combat vulnerabilities for all to see, reducing their Damage Reduction, Deflection, and Concentration.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Fireball',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/4e/Fireball_icon.png',
        name: 'Fireball',
        speed: 'Fast',
        range: '',
        area: '2.5m Radius',
        duration: '',
        effects: '<ul><li>AoE: 25-35 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" class="mw-redirect" title="Burn">Burn</a> damage</li></ul>',
        description: 'Summons a flaming ball of molten earth that explodes at a targeted location, causing Burn damage to all in the area of effect.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Kalakoth%27s_Minor_Blights',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8e/Kalakoths_minor_blights_icon.png',
        name: 'Kalakoth\'s Minor Blights',
        speed: 'Average',
        range: '',
        area: '',
        duration: '60.0 seconds',
        effects: '<ul><li>Summon Weapon: <a href="https://pillarsofeternity.fandom.com/wiki/Kalakoth%27s_Minor_Blight" title="Kalakoth&#39;s Minor Blight">Kalakoth\'s Minor Blight</a> until weapon changed for 60.0 sec</li></ul>',
        description: 'Creates a ball of energy in the caster\'s hand that can be thrown at an enemy, causing Burn, Freeze, Corrode, or Shock damage to anyone caught in the area of effect - blights are continually replenished until the spell ends.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Displaced_Image',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/75/Llengraths_displaced_image_icon.png',
        name: 'Llengrath\'s Displaced Image',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Caster: +25 <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a>, +20 <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" class="mw-redirect" title="Reflex">Reflex</a>, +50% of incoming <a href="https://pillarsofeternity.fandom.com/wiki/Hits" class="mw-redirect" title="Hits">Hits</a> converted to <a href="https://pillarsofeternity.fandom.com/wiki/Grazes" class="mw-redirect" title="Grazes">Grazes</a> (<a href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a> or <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" class="mw-redirect" title="Reflex">Reflex</a> only) for 45.0 sec</li></ul>',
        description: 'Causes the caster to appear visually displaced, increasing their Deflection and Reflex for the duration. Additionally, many Deflection and Reflex attacks that score Hits will be converted to Grazes.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Minoletta%27s_Bounding_Missiles',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/dd/Minolettas_bounding_missiles_icon.png',
        name: 'Minoletta\'s Bounding Missiles',
        speed: 'Average',
        range: '',
        area: 'Target + 2 Foe Jump Targets',
        duration: '',
        effects: '<ul><li>Target: 15-23 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" class="mw-redirect" title="Pierce">Pierce</a> Damage</li><li>Foe Jump Targets (x2): Applies the same effect as Target</li></ul>',
        description: 'Summons three missiles that pierce through the target and leap to two additional targets, each.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Noxious_Burst',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/05/Noxious_burst_icon.png',
        name: 'Noxious Burst',
        speed: 'Average',
        range: '',
        area: '2.5m Radius',
        duration: '10.0 seconds',
        effects: '<ul><li>AoE: 30-42 <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" class="mw-redirect" title="Corrode">Corrode</a> Damage, <a href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a> (<a href="https://pillarsofeternity.fandom.com/wiki/Poison" class="mw-redirect" title="Poison">Poison</a>) for 10.0 sec</li></ul>',
        description: 'Spews forth a poisonous cloud of foulness that causes Corrode damage and leaves victims Sickened.',
    },
    {
        level: '5',
        link: 'https://pillarsofeternity.fandom.com/wiki/Ryngrim%27s_Repulsive_Visage',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/a0/Ryngrims_repulsive_visage_icon.png',
        name: 'Ryngrim\'s Repulsive Visage',
        speed: 'Average',
        range: '',
        area: 'Foe Target + 1.25m Radius from Caster',
        duration: '15.0 seconds',
        effects: '<ul><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a> for 2 seconds</li><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a> for 2 seconds</li></ul>',
        description: 'The caster\'s face becomes a nightmarish mask of rotting, insect-infested flesh or other images of unspeakable horror, compelling all nearby foes to become Terrified and Sickened.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Confusion',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/15/Confusion_icon.png',
        name: 'Confusion',
        speed: 'Average',
        range: '',
        area: '2.5m Radius',
        duration: '8.0 seconds',
        effects: '<ul><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Confused" class="mw-redirect" title="Confused">Confused</a> for 8.0 sec</li></ul>',
        description: 'Infects the minds of enemies in the area of effect with delirium, Confusing them.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Dimensional_Shift',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/98/Dimensional_shift_icon.png',
        name: 'Dimensional Shift',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '1.0 second',
        effects: '<ul><li>Foe Beam: <a href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a> for 5 seconds</li></ul>',
        description: 'Switches the locations of the caster and one ally, leaving a shockwave between them that Stuns all caught in the line of fire.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Essential_Phantom',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/3a/Essential_phantom_icon.png',
        name: 'Essential Phantom',
        speed: 'Average',
        range: '',
        area: '',
        duration: '30.0 seconds',
        effects: '<ul><li>Summon: <a href="https://pillarsofeternity.fandom.com/wiki/Wizard_Duplicate?action=edit&amp;redlink=1" class="new" title="Wizard Duplicate (page does not exist)">Wizard Duplicate</a></li></ul>',
        description: 'Creates a ghostly double of the caster, causing Shock damage to enemies hit by it.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Flame_Shield',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8b/Flame_shield_icon.png',
        name: 'Flame Shield',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Caster: +10 <a href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction">Damage Reduction</a> (<a href="https://pillarsofeternity.fandom.com/wiki/Freeze" class="mw-redirect" title="Freeze">Freeze</a>) for 45.0 sec</li><li>Characters hitting Caster (45.0 sec): 10-15 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" class="mw-redirect" title="Burn">Burn</a> Damage</li></ul>',
        description: 'Engulfs the caster in fire, increasing their Freeze Damage Reduction and causing Burn damage to anyone who damages them with a melee attack.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Ironskin',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/ac/Ironskin_icon.png',
        name: 'Ironskin',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '',
        effects: '<ul><li>Caster: +8&#160;<a href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction">Damage Reduction</a> until <a href="https://pillarsofeternity.fandom.com/wiki/Hit" class="mw-redirect" title="Hit">Hit</a> or <a href="https://pillarsofeternity.fandom.com/wiki/Crit" class="mw-redirect" title="Crit">Critically</a> hit</li></ul>',
        description: 'Transmutes the caster\'s skin into iron, adding significantly to their Damage Reduction. This effect lasts for up to ten attacks.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Mental_Shields',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/52/Llengraths_mental_shields_icon.png',
        name: 'Llengrath\'s Mental Shields',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Caster: Prevents <a href="https://pillarsofeternity.fandom.com/wiki/Charmed" class="mw-redirect" title="Charmed">Charmed</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Dominated" class="mw-redirect" title="Dominated">Dominated</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Distracted" class="mw-redirect" title="Distracted">Distracted</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Dazed" class="mw-redirect" title="Dazed">Dazed</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Confused" class="mw-redirect" title="Confused">Confused</a> (2 times) for 45.0 sec</li></ul>',
        description: 'The caster gains immunity to the Charmed, Confused, Dazed, Distracted, Dominated, Frightened, Stunned, and Terrified afflictions. The shields will negate two attacks from each affliction type.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Physical_Shields',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/2f/Llengraths_physical_shields_icon.png',
        name: 'Llengrath\'s Physical Shields',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Caster: Prevent <a href="https://pillarsofeternity.fandom.com/wiki/Blinded" class="mw-redirect" title="Blinded">Blinded</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Stuck" class="mw-redirect" title="Stuck">Stuck</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Prone" class="mw-redirect" title="Prone">Prone</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Petrified" class="mw-redirect" title="Petrified">Petrified</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a> (2 times) for 45.0 sec</li></ul>',
        description: 'The caster gains immunity to the Blinded, Paralyzed, Petrified, Prone, Sickened, Stuck, and Weakened afflictions. The shields protect against two attacks from each affliction.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Maura%27s_Writhing_Tentacles',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/32/Mauras_writhing_tentacles_icon.png',
        name: 'Maura\'s Writhing Tentacles',
        speed: 'Slow',
        range: '',
        area: '',
        duration: '15.0 seconds',
        effects: '<ul><li>Summon: 3x <a href="https://pillarsofeternity.fandom.com/wiki/Tentacle?action=edit&amp;redlink=1" class="new" title="Tentacle (page does not exist)">Tentacles</a></li></ul>',
        description: 'Summons a trio of powerful tentacles that cannot move, but can inflict Crush and Corrode damage and the Stuck affliction on anyone they hit.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Minoletta%27s_Concussive_Missiles',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/73/Minolettas_concussive_missiles_icon.png',
        name: 'Minoletta\'s Concussive Missiles',
        speed: 'Average',
        range: '',
        area: 'Target + 1.25m Radius',
        duration: '',
        effects: '<ul><li>Target: 15-25 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" class="mw-redirect" title="Crush">Crush</a> Damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235317" decoding="async" width="18" height="18" /></a>)</li><li>Foe AoE: 10-15 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" class="mw-redirect" title="Crush">Crush</a> Damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235341" decoding="async" width="18" height="18" /></a>)</li></ul>',
        description: 'Fires five missiles of pure force at the target, causing a shockwave of Crushing damage to foes close to the impact.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Minor_Arcane_Reflection',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/c/c3/Minor_arcane_reflection_icon.png',
        name: 'Minor Arcane Reflection',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '60.0 seconds',
        effects: '<ul><li>Caster: Minor Spell Reflection for 60.0 sec (10 spell levels up to 3rd level reflected back at enemy)</li></ul>',
        description: 'Creates a field of arcane energy around the caster, causing hostile targeted spells up to 3rd level to be reflected back at their casters (for a total of ten spell levels).',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Minor_Grimoire_Imprint',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/29/Minor_grimoire_imprint_icon.png',
        name: 'Minor Grimoire Imprint',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '15.0 seconds',
        effects: '<ul><li>Foe Target: Steals 3 spells of Level 3 or lower for 15.0 sec</li></ul>',
        description: 'Gives the caster access to up to three \'free\' 3rd or lower level spells from the target\'s (wizard, druid, or priest) spell list. The wizard can subsequently cast those spells an unlimited number of times for the duration.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Ninagauth%27s_Death_Ray',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8a/Ninagauths_death_ray_icon.png',
        name: 'Ninagauth\'s Death Ray',
        speed: 'Average',
        range: '',
        area: '',
        duration: '10.0 seconds',
        effects: '<ul><li>Foe Target: 6-12 <a href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> Damage per 1.0 sec</li><li>Beam: Applies the same effect as Foe Target</li></ul>',
        description: 'This more powerful variant of the common Ray of Fire spell inflicts Raw damage, attacks the targets\' Fortitude, and only affects enemies.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Ninagauth%27s_Shadowflame',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/58/Ninagauths_shadowflame_icon.png',
        name: 'Ninagauth\'s Shadowflame',
        speed: 'Fast',
        range: '',
        area: '2.5m Radius',
        duration: '6.0 seconds',
        effects: '<ul><li>AoE: 35-45 <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" class="mw-redirect" title="Freeze">Freeze</a> Damage&#160;(+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235341" decoding="async" width="18" height="18" /></a>)</li><li>If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a> for 6.0 sec (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235327" decoding="async" width="18" height="18" /></a>)</li></ul>',
        description: 'A curious variant of the ever-popular Fireball, Ninagauth\'s Shadowflame causes Freeze damage and Paralyzes anyone caught in the area of effect.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Pull_of_Eora',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/55/Pull_of_eora_icon.png',
        name: 'Pull of Eora',
        speed: 'Fast',
        range: '',
        area: '2.5m Radius',
        duration: '15.0 seconds',
        effects: '<ul><li>AoE: -1 <a href="https://pillarsofeternity.fandom.com/wiki/Move_Speed" title="Move Speed">Move Speed</a> for 5.0 sec, 6m Pull</li></ul>',
        description: 'The wizard summons a black sphere that draws all nearby enemies toward it each time it pulses.',
    },
    {
        level: '7',
        link: 'https://pillarsofeternity.fandom.com/wiki/Wall_of_Flame',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/b/bd/Wall_of_flame_icon.png',
        name: 'Wall of Flame',
        speed: 'Average',
        range: '',
        area: '20m Wall',
        duration: '30.0 seconds',
        effects: '<ul><li>Hazard AoE: 5-8 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235248" decoding="async" width="18" height="18" /></a> damage</li></ul>',
        description: 'Generates a fearsome vertical sheet of flame, inflicting Burn damage on anyone moving through it.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Arkemyr%27s_Wondrous_Torment',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/03/Arkemyrs_wondrous_torment_icon.png',
        name: 'Arkemyr\'s Wondrous Torment',
        speed: 'Average',
        range: '',
        area: '',
        duration: '10.0 seconds',
        effects: '<ul><li>Foe Target: -10 <a href="https://pillarsofeternity.fandom.com/wiki/Resolve" title="Resolve">Resolve</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Intellect" title="Intellect">Intellect</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Perception" title="Perception">Perception</a> for 10.0 sec</li></ul>',
        description: 'Drains the target\'s Resolve, Intellect, and Perception, creating two less powerful versions of the effect that jump to nearby enemies when the first effect ends.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Blast_of_Frost',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/55/Blast_of_frost_icon.png',
        name: 'Blast of Frost',
        speed: 'Average',
        range: '',
        area: 'Length: 5.0m 75° Cone',
        duration: '',
        effects: '<ul><li>AoE: 50-80 <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png/revision/latest/scale-to-width-down/18?cb=20170909202622" decoding="async" width="18" height="18" /></a> damage</li></ul>',
        description: 'Creates a bitter surge of ice and freezing cold air, inflicting Freeze damage on anyone caught in the conical area of effect.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Call_to_Slumber',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/ea/Call_to_slumber_icon.png',
        name: 'Call to Slumber',
        speed: 'Average',
        range: '',
        area: '2.5m Radius',
        duration: '6.0 seconds',
        effects: '<ul><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Unconscious" title="Unconscious">Unconscious</a> for 6.0 sec</li></ul>',
        description: 'Causes a group of enemies to momentarily fall asleep, falling Unconscious for a short duration.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Citzal%27s_Spirit_Lance',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/c/cb/Citzals_spirit_lance_icon.png',
        name: 'Citzal\'s Spirit Lance',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Summon Weapon: <a href="https://pillarsofeternity.fandom.com/wiki/Citzal%27s_Spirit_Lance_(item)" title="Citzal&#39;s Spirit Lance (item)">Citzal\'s Spirit Lance</a></li></ul>',
        description: 'Creates a pike of pure magical force, that deals Pierce damage and causes a foe-only Blast explosion like wands do.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Form_of_the_Helpless_Beast',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d1/Form_of_the_helpless_beast_icon.png',
        name: 'Form of the Helpless Beast',
        speed: 'Slow',
        range: '',
        area: '',
        duration: '10.0 seconds',
        effects: '<ul><li>Foe Target: Helpless Beast Form for 10.0 sec</li></ul>',
        description: 'Transforms a single kith enemy (aumaua, dwarf, elf, godlike, human, or orlan) into a pig. The pig has very poor defenses but can move quickly.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Safeguard',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/a5/Llengraths_safeguard_icon.png',
        name: 'Llengrath\'s Safeguard',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '60.0 seconds',
        effects: '<ul><li>Caster: +20 All <a href="https://pillarsofeternity.fandom.com/wiki/Defense" title="Defense">Defenses</a>, +10 <a href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction">Damage Reduction</a> for 60.0 sec</li></ul>',
        description: 'An insidious magical contingency activates when the caster hits 50% Endurance. He or she immediately knocks all immediately close enemies prone while gaining a Damage Reduction and Defense bonus for a short time.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Malignant_Cloud',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/69/Malignant_cloud_icon.png',
        name: 'Malignant Cloud',
        speed: 'Average',
        range: '',
        area: '2.5m Radius',
        duration: '10.0 seconds',
        effects: '<ul><li>AoE: 15-22 <a href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage</li></ul>',
        description: 'Generates a cloud of virulent poison, inflicting Raw damage to anyone in the cloud every few seconds.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Ninagauth%27s_Bitter_Mooring',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/80/Ninagauths_bitter_mooring_icon.png',
        name: 'Ninagauth\'s Bitter Mooring',
        speed: 'Average',
        range: '',
        area: '',
        duration: '15.0 seconds',
        effects: '<ul><li>Target: 20-28 <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" class="mw-redirect" title="Freeze">Freeze</a> Damage, <a href="https://pillarsofeternity.fandom.com/wiki/Stuck" class="mw-redirect" title="Stuck">Stuck</a> for 3.0 sec</li><li>Beam: Applies the same effect as Target</li></ul>',
        description: 'The target is hit with a Stuck affliction and becomes an anchor for a frigid ray of energy from the wizard that does Freeze damage to creatures in its path.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Ryngrim%27s_Enervating_Terror',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/a6/Ryngrims_enervating_terror_icon.png',
        name: 'Ryngrim\'s Enervating Terror',
        speed: 'Average',
        range: '20m',
        area: '2.5m Radius',
        duration: '20.0 seconds',
        effects: '<ul><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a></li><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a></li></ul>',
        description: 'Causes enemies in the area of effect to envision their worst fears, causing them to be Weakened and Terrified.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Torrent_of_Flame',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/f9/Torrent_of_flame_icon.png',
        name: 'Torrent of Flame',
        speed: 'Fast',
        range: '',
        area: '2.5m Radius from Caster',
        duration: '',
        effects: '<ul><li>AoE: 40-55 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235248" decoding="async" width="18" height="18" /></a> damage</li></ul>',
        description: 'Instantiates a terrifying inferno of flame around the caster, inflicting Burn damage on everyone nearby.',
    },
    {
        level: '9',
        link: 'https://pillarsofeternity.fandom.com/wiki/Wall_of_Force',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/51/Wall_of_force_icon.png',
        name: 'Wall of Force',
        speed: 'Average',
        range: '',
        area: '20m Wall',
        duration: '30.0 seconds',
        effects: '<ul><li>Hazard AoE: 4-6 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235303" decoding="async" width="18" height="18" /></a> damage</li><li>Hazard AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a> for 20 seconds</li></ul>',
        description: 'Creates a semi-permeable barrier that inflicts Crush damage and Hobbles enemies when they pass through it, but leaves allies unscathed.',
    },
    {
        level: '11',
        link: 'https://pillarsofeternity.fandom.com/wiki/Arcane_Reflection',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/df/Arcane_reflection_icon.png',
        name: 'Arcane Reflection',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Caster: Spell Reflection for 45.0 sec (15 spell levels up to 5th level reflected back at enemy)</li></ul>',
        description: 'Creates a field of arcane energy around the caster, reflecting hostile targeted spells up to 5th level back at their casters (for a total of 15 spell levels).',
    },
    {
        level: '11',
        link: 'https://pillarsofeternity.fandom.com/wiki/Arkemyr%27s_Capricious_Hex',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/da/Arkemyrs_capricious_hex_icon.png',
        name: 'Arkemyr\'s Capricious Hex',
        speed: 'Average',
        range: '',
        area: '5.0m Radius',
        duration: '12.0 seconds',
        effects: '<ul><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Dazed" class="mw-redirect" title="Dazed">Dazed</a> for 10 seconds</li><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a> for 12 seconds</li><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a> for 6 seconds</li></ul>',
        description: 'Unleashes a volatile hex upon enemies in the area of effect, causing them to become either Dazed, Sickened, or Paralyzed, depending on its own mysterious whims.',
    },
    {
        level: '11',
        link: 'https://pillarsofeternity.fandom.com/wiki/Chain_Lightning',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/de/Chain_lightning_icon.png',
        name: 'Chain Lightning',
        speed: 'Average',
        range: '',
        area: 'Target + 6 Foe Jump Targets',
        duration: '',
        effects: '<ul><li>Target: 30-50 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235346" decoding="async" width="18" height="18" /></a> damage</li><li>Foe Jump Targets (x6): 30-50 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235346" decoding="async" width="18" height="18" /></a> damage</li></ul>',
        description: 'The caster calls forth a tremendous bolt of electricity that arcs directly to a single target and then jumps between up to six nearby enemies. Others in the area of effect are not harmed by the arcane lightning.',
    },
    {
        level: '11',
        link: 'https://pillarsofeternity.fandom.com/wiki/Citzal%27s_Martial_Power',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/0b/Citzals_martial_power_icon.png',
        name: 'Citzal\'s Martial Power',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '30.0 seconds',
        effects: '<ul><li>Self: +20 <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235317" decoding="async" width="18" height="18" /></a>, +20 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a>, +8 <a href="https://pillarsofeternity.fandom.com/wiki/Might" title="Might">Might</a>, +8 <a href="https://pillarsofeternity.fandom.com/wiki/Constitution" title="Constitution">Constitution</a>, +8 <a href="https://pillarsofeternity.fandom.com/wiki/Dexterity" title="Dexterity">Dexterity</a>, Spellcasting disabled</li></ul>',
        description: 'Caster temporarily sacrifices arcane power for martial might. Wizard gains bonuses to Deflection, Accuracy, Might, Constitution and Dexterity, but becomes unable to cast spells or switch grimoires for the duration of the spell.',
    },
    {
        level: '11',
        link: 'https://pillarsofeternity.fandom.com/wiki/Death_Ring',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/fe/Death_ring_icon.png',
        name: 'Death Ring',
        speed: 'Average',
        range: '',
        area: '5.0m Radius from Caster',
        duration: '',
        effects: '<ul><li>Foe AoE: 30-45 <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235258" decoding="async" width="18" height="18" /></a> damage, Destroyed</li></ul>',
        description: 'Calls a black ring of necrotic energy into being that spreads out in all directions, causing Corrode damage to enemies it touches and potentially destroying those with low Endurance.',
    },
    {
        level: '11',
        link: 'https://pillarsofeternity.fandom.com/wiki/Gaze_of_the_Adragan',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/c/ce/Gaze_of_the_adragan_icon.png',
        name: 'Gaze of the Adragan',
        speed: 'Average',
        range: '',
        area: '1.5m Radius',
        duration: '6.0 seconds',
        effects: '<ul><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Petrified" class="mw-redirect" title="Petrified">Petrified</a> for 6.0 sec</li></ul>',
        description: 'Gives the caster the mystifying gaze of the adra creature that provides the spell\'s namesake, Petrifying enemies within the area of effect.',
    },
    {
        level: '11',
        link: 'https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Blunt_Wisdom',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/46/Llengraths_blunt_wisdom_icon.png',
        name: 'Llengrath\'s Blunt Wisdom',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 sec',
        effects: '<ul><li>Caster: Summon Weapon: <a href="https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Blunt_Wisdom_(item)" title="Llengrath&#39;s Blunt Wisdom (item)">Llengrath\'s Blunt Wisdom</a> for 45.0 sec</li></ul>',
        description: 'The wizard summons a rod that hurls a ball of magical energy. When the ball arrives at its target, it hovers for a few moments before exploding, inflicting terrible Raw damage on nearby enemies.',
    },
    {
        level: '11',
        link: 'https://pillarsofeternity.fandom.com/wiki/Minoletta%27s_Precisely_Piercing_Burst',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/70/Minolettas_precisely_piercing_burst_icon.png',
        name: 'Minoletta\'s Precisely Piercing Burst',
        speed: 'Fast',
        range: '',
        area: '3.0m Radius from Caster',
        duration: '',
        effects: '<ul><li>Foe AoE: 50-68 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" class="mw-redirect" title="Pierce">Pierce</a> Damage, 10 <a href="https://pillarsofeternity.fandom.com/wiki/DR" class="mw-redirect" title="DR">DR</a> bypass</li></ul>',
        description: 'Creates a burst of deadly force around the caster, causing any enemies in the immediate vicinity to take Pierce damage - bypassing their Damage Reduction.',
    },
    {
        level: '11',
        link: 'https://pillarsofeternity.fandom.com/wiki/Ninagauth%27s_Freezing_Pillar',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/2f/Ninagauths_freezing_pillar_icon.png',
        name: 'Ninagauth\'s Freezing Pillar',
        speed: 'Average',
        range: '',
        area: '2.5m Radius',
        duration: '9.0 seconds',
        effects: '<ul><li>Foe AoE: 22-26 <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" class="mw-redirect" title="Freeze">Freeze</a> Damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235341" decoding="async" width="18" height="18" /></a>)</li><li>If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a> for 3.0 sec (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235327" decoding="async" width="18" height="18" /></a>)</li></ul>',
        description: 'Calls down an enormous spike of ice, pulsing Freeze damage on enemies in the area of effect and creating an intense circle of frost that can Hobble foes it touches.',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/Concelhaut%27s_Crushing_Doom',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/5f/Concelhauts_crushing_doom_icon.png',
        name: 'Concelhaut\'s Crushing Doom',
        speed: 'Average',
        range: '',
        area: '',
        duration: '10.0 seconds',
        effects: '<ul><li>Target: 20-30 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235303" decoding="async" width="18" height="18" /></a> damage (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235317" decoding="async" width="18" height="18" /></a>)</li><li>If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Prone" class="mw-redirect" title="Prone">Prone</a> for 3 seconds (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235341" decoding="async" width="18" height="18" /></a>)</li><li>Hammer attacks five times, at +5 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> for each additional attack</li></ul>',
        description: 'A truly unique spell, Concelhaut\'s Crushing Doom summons an enormous magical hammer that repeatedly slams down into its target, doing Crush damage and knocking them Prone. The hammer strikes repeatedly, becoming larger, more accurate, and more damaging each time.',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/Delayed_Fireball',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/48/Delayed_fireball_icon.png',
        name: 'Delayed Fireball',
        speed: 'Fast',
        range: '',
        area: '2.5m Radius',
        duration: '',
        effects: '<ul><li>AoE: 50-65 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235248" decoding="async" width="18" height="18" /></a> damage</li></ul>',
        description: 'The wizard hurls out a tiny ball of flame that sits for a fixed amount of time before exploding for heavy Burn damage.',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Siphoning_Image',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/40/Llengraths_siphoning_image_icon.png',
        name: 'Llengrath\'s Siphoning Image',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Characters hitting Caster (45.0 sec): 3-8 <a href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> Damage, -20 <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a> for 15.0 sec (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png/revision/latest/scale-to-width-down/18?cb=20170909202632" decoding="async" width="18" height="18" /></a>)</li><li>Target: Applies the same effect as Characters hitting Caster (45.0 sec)</li><li>Caster: +40 <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a>, +30 <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" class="mw-redirect" title="Reflex">Reflex</a>, +50% of incoming <a href="https://pillarsofeternity.fandom.com/wiki/Hits" class="mw-redirect" title="Hits">Hits</a> converted to <a href="https://pillarsofeternity.fandom.com/wiki/Grazes" class="mw-redirect" title="Grazes">Grazes</a> (<a href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a> or <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" class="mw-redirect" title="Reflex">Reflex</a> only) for 45.0 sec</li></ul>',
        description: 'Causes the caster to appear visually displaced, increasing their Deflection and Reflex for the duration. Additionally, many Deflection and Reflex attacks that score Hits will be converted to Grazes.',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Warding_Staff',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d5/Llengraths_warding_staff_icon.png',
        name: 'Llengrath\'s Warding Staff',
        speed: 'Fast',
        range: '',
        area: '5.0m Radius from Caster',
        duration: '30.0 seconds',
        effects: '<ul><li>AoE: 2.5m Push</li><li>Caster: Summon Weapon: <a href="https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Warding_Staff_(weapon)?action=edit&amp;redlink=1" class="new" title="Llengrath&#39;s Warding Staff (weapon) (page does not exist)">Llengrath\'s Warding Staff</a> for 30.0 sec</li></ul>',
        description: 'This spell conjures a powerful quarterstaff that adds Deflection and pushes enemies away with a Hobbled effect on each successful attack. The summoning itself also pushes everyone (including allies) away from the caster.',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/Ninagauth%27s_Killing_Bolt',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/09/Ninagauths_killing_bolt_icon.png',
        name: 'Ninagauth\'s Killing Bolt',
        speed: 'Slow',
        range: '',
        area: '',
        duration: '',
        effects: '<ul><li>Target: 75 <a href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> Damage</li></ul>',
        description: 'This spell inflicts a heavy amount of Raw damage to the target. Any non-Spirit felled by the attack will summon a Spectre under the caster\'s control.',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/Substantial_Phantom',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/b/bd/Substantial_phantom_icon.png',
        name: 'Substantial Phantom',
        speed: 'Average',
        range: '6m',
        area: '',
        duration: '30.0 seconds',
        effects: '<ul><li>Summon: <a href="https://pillarsofeternity.fandom.com/wiki/Wizard_Duplicate?action=edit&amp;redlink=1" class="new" title="Wizard Duplicate (page does not exist)">Wizard Duplicate</a></li></ul>',
        description: 'Substantial Phantom is an advanced version of Essential Phantom, creating an independent copy of the wizard that can cast a small set of low-level spells (Minoletta\'s Minor Missiles, Necrotic Lance, and Arduous Delay of Motion). Due to the advanced nature of the spell, the copy from Substantial Phan',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/Tayn%27s_Chaotic_Orb',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d4/Tayns_chaotic_orb_icon.png',
        name: 'Tayn\'s Chaotic Orb',
        speed: 'Average',
        range: '10m + 5m Jump',
        area: 'Foe Target + 5 Foe Jump Targets',
        duration: '8.0 seconds',
        effects: '<ul><li>Foe Target: 20-30 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235303" decoding="async" width="18" height="18" /></a> damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235317" decoding="async" width="18" height="18" /></a>)</li><li>If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Petrified" class="mw-redirect" title="Petrified">Petrified</a> for 3 seconds, <a href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a> for 4 seconds, <a href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a> for 7 seconds, <a href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a> for 8 seconds, <a href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a> for 5 seconds, <a href="https://pillarsofeternity.fandom.com/wiki/Blinded" class="mw-redirect" title="Blinded">Blinded</a> for 6 seconds (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png/revision/latest/scale-to-width-down/18?cb=20170909202632" decoding="async" width="18" height="18" /></a>)</li><li>Foe Jump Targets (x5): Applies the same effects as Foe Target</li></ul>',
        description: 'Named for the eccentric Aedyran wizard Tayn, the chaotic orb bounces between a number of enemies, dealing damage and inflicting a variety of negative Afflictions including Petrified, Paralyzed, Weakened, Sickened, Stunned, and Blinded.',
    },
    {
        level: '13',
        link: 'https://pillarsofeternity.fandom.com/wiki/Wall_of_Draining',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/02/Wall_of_draining_icon.png',
        name: 'Wall of Draining',
        speed: 'Average',
        range: '',
        area: '20m Wall',
        duration: '30.0 seconds',
        effects: '<ul><li>Foe AoE: Steal 4 seconds duration from each beneficial effect on the target for 20 seconds</li></ul>',
        description: 'Enemies passing through or standing in this wall will lose time from any of their timed beneficial status effects.  For each second drained, the Wizard gains duration on any beneficial status effects they have.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/Caedebald%27s_Blackbow',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/76/Caedebalds_blackbow_icon.png',
        name: 'Caedebald\'s Blackbow',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '45.0 seconds',
        effects: '<ul><li>Summon Weapon: <a href="https://pillarsofeternity.fandom.com/wiki/Caedebald%27s_Blackbow_(item)" title="Caedebald&#39;s Blackbow (item)">Caedebald\'s Blackbow</a></li></ul>',
        description: 'The wizard summons a frightful bow that does Corrode damage to enemies and leaves them Terrified. Each bolt of energy the wizard fires bounces to one additional target.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/Kalakoth%27s_Freezing_Rake',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/35/Kalakoths_freezing_rake_icon.png',
        name: 'Kalakoth\'s Freezing Rake',
        speed: 'Fast',
        range: '',
        area: 'Length: 5.0m',
        duration: '8.0 seconds',
        effects: '<ul><li>Target: 60-75 <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" class="mw-redirect" title="Freeze">Freeze</a> Damage (+15 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs&#160;<a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235341" decoding="async" width="18" height="18" /></a>)</li><li>If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a> for 8.0 sec (+15 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235327" decoding="async" width="18" height="18" /></a>)</li></ul>',
        description: 'A ghostly, skeletal hand rakes across the area, doing Freeze damage to enemies in the area, leaving them Weakened and Hobbled.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Dread_Haze',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e6/Llengraths_dread_haze_icon.png',
        name: 'Llengrath\'s Dread Haze',
        speed: 'Average',
        range: '',
        area: 'Foe Target + 5.0m Radius',
        duration: '20.0 seconds',
        effects: '<ul><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Health" class="mw-redirect" title="Health">Health</a> and <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> concealed for 20.0 sec, <a href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a> for 20.0 sec</li></ul>',
        description: 'Fills targets with an intense malaise that leaves them Sickened and incapable of evaluating their Endurance.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/Llengrath%27s_Superior_Elemental_Bulwark',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/52/Llengraths_superior_elemental_bulwark_icon.png',
        name: 'Llengrath\'s Superior Elemental Bulwark',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '30.0 seconds',
        effects: '<ul><li>Caster: 100-pt <a href="https://pillarsofeternity.fandom.com/wiki/Burn" class="mw-redirect" title="Burn">Burn</a> Damage Shield, 100-pt <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" class="mw-redirect" title="Freeze">Freeze</a> Damage Shield, 100-pt <a href="https://pillarsofeternity.fandom.com/wiki/Shock" class="mw-redirect" title="Shock">Shock</a> Damage Shield, 100-pt <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" class="mw-redirect" title="Corrode">Corrode</a> Damage Shield for 30.0 sec</li></ul>',
        description: 'The wizard is protected by elemental shields that guard him or her against Burn, Corrode, Freeze, and Shock damage until they are overwhelmed or the duration expires.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/Major_Grimoire_Imprint',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/ff/Major_grimoire_imprint_icon.png',
        name: 'Major Grimoire Imprint',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '60.0 seconds',
        effects: '<ul><li>Foe Target: Steals 3 spells of Level 7 or lower for 60.0 sec</li></ul>',
        description: 'Allows the wizard to temporarily "borrow" druid, priest, or wizard spells of 7th level or lower. For a short duration, the wizard can cast the stolen spells freely.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/Minoletta%27s_Piercing_Sigil',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/81/Minolettas_piercing_sigil_icon.png',
        name: 'Minoletta\'s Piercing Sigil',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '20.0 seconds',
        effects: '<ul><li>Characters hitting Caster (20.0 sec): 18-25 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" class="mw-redirect" title="Pierce">Pierce</a> Damage, 3.0m Push (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235317" decoding="async" width="18" height="18" /></a>)</li><li>If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a> for 1.5 sec (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235327" decoding="async" width="18" height="18" /></a>)</li></ul>',
        description: 'The wizard invokes the sigil of the famed Vailian wizard Minoletta. When he or she is struck in melee, the sigil retaliates with Pierce damage, pushing the target back and leaving them Stunned.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/Spell_Steal',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/ff/Major_grimoire_imprint_icon.png',
        name: 'Spell Steal',
        speed: 'Fast',
        range: '',
        area: '',
        duration: '60.0 seconds',
        effects: '<ul><li>For Target: Steals 3 spells up to 5th level</li></ul>',
        description: 'Allows the wizard to temporarily "borrow" druid, priest, or wizard spells of 7th level or lower. For a short duration, the wizard can cast the stolen spells freely.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/Wall_of_Many_Colors',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/4f/Wall_of_many_colors_icon.png',
        name: 'Wall of Many Colors',
        speed: 'Average',
        range: '12m',
        area: '20m Wall',
        duration: '12.0 seconds',
        effects: '<ul><li>Red: 25-40 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235248" decoding="async" width="18" height="18" /></a> damage</li><li>Orange: 35 <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235258" decoding="async" width="18" height="18" /></a>&#160;damage</li><li>Yellow: 20-50 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235346" decoding="async" width="18" height="18" /></a> damage</li><li>Green: 20-35 <a href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage</li><li>Blue: <a href="https://pillarsofeternity.fandom.com/wiki/Petrified" class="mw-redirect" title="Petrified">Petrified</a> for 8 seconds</li><li>Indigo: <a href="https://pillarsofeternity.fandom.com/wiki/Dominated" class="mw-redirect" title="Dominated">Dominated</a> for 8 seconds</li><li>Violet: <a href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a> for 10 seconds</li></ul>',
        description: 'Summons a scintillating wall of varied colors that inflicts varied damage and afflictions on enemies passing through it.',
    },
    {
        level: '15',
        link: 'https://pillarsofeternity.fandom.com/wiki/Wilting_Wind',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/a5/Wilting_wind_icon.png',
        name: 'Wilting Wind',
        speed: 'Slow',
        range: '10m',
        area: '4.0m Radius',
        duration: '12.0 seconds',
        effects: '<ul><li>AoE: 50-60 <a href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage</li><li>AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a></li></ul>',
        description: 'A parching wind blows across the battlefield, inflicting Raw damage on anyone in the area and leaving them Weakened.',
    },
];
