const barbarianPassiveImageLink = 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Barbarian_passive_icon.png';

export default {
    name: 'Barbarian',
    endurancePerLevel: 16,
    healthMultiplier: 6,
    accuracy: 25,
    deflection: 15,
    skillBonuses: {
        athletics: +2,
        survival: +1
    },
    baseAbility: {
        name: 'Carnage',
        link: 'https://pillarsofeternity.fandom.com/wiki/Carnage',
        imageLink: barbarianPassiveImageLink,
        level: '1',
        activation: 'Passive',
        effects: '<ul><li>Causes 0.66x <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">damage</a> to enemies in a 1.5m radius from the targeted enemy</li></ul>',
        speed: '',
        duration: '',
        area: '1.5m Radius from Target',
        description: 'The barbarian\'s attacks become so forceful as to impact others around the target enemy. For every successful melee attack, the barbarian makes reduced-damage attacks at all other enemies within a short distance of the target.',
    },
    abilities: [
        {
            name: 'Barbaric Yell',
            link: 'https://pillarsofeternity.fandom.com/wiki/Barbaric_Yell',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/af/Barbaric_yell_icon.png',
            level: '1',
            activation: 'Active (2 per Encounter)',
            effects: '<ul><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a> for 12.0 seconds</li></ul>',
            speed: 'Average',
            duration: '',
            area: '5.0m Radius from Caster',
            description: 'Lets out a terrifying yell, frightening enemies in the area of effect.',
        },
        {
            name: 'Frenzy',
            link: 'https://pillarsofeternity.fandom.com/wiki/Frenzy',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/0b/Frenzy_icon.png',
            level: '1',
            activation: 'Active (1 per Encounter)',
            effects: '<ul><li>+4 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Might" title="Might">Might</a></li><li>+4 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Constitution" title="Constitution">Constitution</a></li><li>x1.33 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Attack_Speed" title="Attack Speed">Attack Speed</a></li><li>-10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a></li><li><a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Health" class="mw-redirect" title="Health">Health</a> and <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> concealed</li></ul>',
            speed: 'Average',
            duration: '12.0 seconds',
            area: 'Self',
            description: 'Sends the barbarian into a frenzied state, granting a Might, Constitution, and Attack Speed bonus but causing a Deflection penalty against incoming attacks. While the barbarianвЂ™s Frenzy is active, his or her Endurance and Health are concealed.',
        },
        {
            name: 'Blooded',
            link: 'https://pillarsofeternity.fandom.com/wiki/Blooded',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Barbarian_passive_icon.png',
            level: '3',
            activation: 'Passive',
            effects: '<ul><li>+25% <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">Damage</a> while <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> below 50%</li></ul>',
            speed: '',
            duration: '',
            area: 'Self',
            description: 'Causes the barbarian to lash out when in pain, granting a bonus to damage for as long as his or her Endurance is below 50%.',
        },
        {
            name: 'Savage Defiance',
            link: 'https://pillarsofeternity.fandom.com/wiki/Savage_Defiance',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/61/Savage_defiance_icon.png',
            level: '3',
            activation: 'Active (1 per Encounter)',
            effects: '<ul><li>+100 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> over 12 seconds</li></ul>',
            speed: 'Instant',
            duration: '12.0 seconds',
            area: 'Self',
            description: 'The barbarian channels his or her own irrepressible determination, regenerating a large amount of Endurance.',
        },
        {
            name: 'Wild Sprint',
            link: 'https://pillarsofeternity.fandom.com/wiki/Wild_Sprint',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/6c/Wild_sprint_icon.png',
            level: '3',
            activation: 'Active (3 per Rest)',
            effects: '<ul><li>+3.5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Move_Speed" title="Move Speed">Move Speed</a></li><li>+12 to all <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Defense" title="Defense">Defenses</a> when <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Melee_Engagement" title="Melee Engagement">Disengaging</a></li><li>Not stopped by <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Engagement" class="mw-redirect" title="Engagement">Engagement</a></li></ul>',
            speed: 'Instant',
            duration: '5.0 seconds',
            area: 'Self',
            description: 'The barbarian becomes able to charge with reckless abandon, allowing him or her to ignore the movement stop of Engagement and gain bonus to all defenses against Disengagement Attacks.',
        },
        {
            name: 'Bloodlust',
            link: 'https://pillarsofeternity.fandom.com/wiki/Bloodlust',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Barbarian_passive_icon.png',
            level: '5',
            activation: 'Passive',
            effects: '<ul><li>+20% <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Attack_Speed" title="Attack Speed">Attack Speed</a> after downing 2 enemies</li></ul>',
            speed: '',
            duration: '8.0 seconds',
            area: 'Self',
            description: 'Imparts an unquenchable bloodlust to the Barbarian, increasing his or her speed temporarily in battle once he or she has personally downed at least two enemies.',
        },
        {
            name: 'Brute Force',
            link: 'https://pillarsofeternity.fandom.com/wiki/Brute_Force',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Barbarian_passive_icon.png',
            level: '5',
            activation: 'Passive',
            effects: '<ul><li>Attacks target <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Fortitude" class="mw-redirect" title="Fortitude">Fortitude</a>, if lower than <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a></li></ul>',
            speed: '',
            duration: '',
            area: 'Self',
            description: 'The barbarian hits so hard that ordinary means of defense can be easily overpowered. On attacks that normally target Deflection, the barbarian will instead attack Fortitude if it is the lower defense.',
        },
        {
            name: 'One Stands Alone',
            link: 'https://pillarsofeternity.fandom.com/wiki/One_Stands_Alone',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Barbarian_passive_icon.png',
            level: '5',
            activation: 'Passive',
            effects: '<ul><li>+2 enemies needed to get <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Flanked" class="mw-redirect" title="Flanked">Flanked</a></li><li>+20% melee <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">damage</a> when adjacent to 2 or more enemies</li></ul>',
            speed: '',
            duration: '',
            area: '',
            description: 'The barbarian makes a courageous stand against all attackers. Grants a melee Damage bonus when the barbarian is adjacent to two or more enemies, and the barbarian cannot be flanked unless Engaged by more than three enemies.',
        },
        {
            name: 'Blood Thirst',
            link: 'https://pillarsofeternity.fandom.com/wiki/Blood_Thirst',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/6c/Blood_thirst_icon.png',
            level: '7',
            activation: 'Passive',
            effects: '<ul><li><a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Recovery_Speed" class="mw-redirect" title="Recovery Speed">Recover</a> immediately after killing an enemy</li></ul>',
            speed: '',
            duration: '',
            area: 'Self',
            description: 'After killing an enemy, the barbarian\'s Recovery is waived, allowing them to attack again immediately.',
        },
        {
            name: 'Thick-skinned',
            link: 'https://pillarsofeternity.fandom.com/wiki/Thick-skinned',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Barbarian_passive_icon.png',
            level: '7',
            activation: 'Passive',
            effects: '<ul><li>+3 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a></li><li>+3 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a></li><li>+3 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
            speed: '',
            duration: '',
            area: 'Self',
            description: 'Toughens the Barbarian\'s naturally thick skin, raising his or her Damage Reduction.',
        },
        {
            name: 'Threatening Presence',
            link: 'https://pillarsofeternity.fandom.com/wiki/Threatening_Presence',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Barbarian_passive_icon.png',
            level: '7',
            activation: 'Passive',
            effects: '<ul><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a> for 3 seconds</li></ul>',
            speed: 'Average',
            duration: '3.0 seconds',
            area: '1.25m Radius from Caster',
            description: 'The barbarian\'s mere presence becomes so intimidating as to fill all approaching enemies with nauseating dread. As long as the barbarian is stationary, nearby enemies may be Sickened.',
        },
        {
            name: 'Barbaric Shout',
            link: 'https://pillarsofeternity.fandom.com/wiki/Barbaric_Shout',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1a/Barbaric_shout_icon.png',
            level: '9',
            activation: 'Active (2 per Rest)',
            effects: '<ul><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a> for 20 seconds</li></ul>',
            speed: 'Average',
            duration: '20 seconds',
            area: '7.5m Radius from Caster',
            description: 'Lets out a dreadful shout, Terrifying enemies in the area of effect.',
        },
        {
            name: 'Vengeful Defeat',
            link: 'https://pillarsofeternity.fandom.com/wiki/Vengeful_Defeat',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Barbarian_passive_icon.png',
            level: '9',
            activation: 'Passive',
            effects: '<ul><li><a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Full_Attack" class="mw-redirect" title="Full Attack">Full Attack</a> on 0 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a></li></ul>',
            speed: '',
            duration: '',
            area: '2.0m Radius from Caster',
            description: 'Exacts a final revenge when the Barbarian is reduced to 0 Endurance, causing him or her to perform instant Carnage Full Attacks at everyone in range.',
        },
        {
            name: 'Eye of the Storm',
            link: 'https://pillarsofeternity.fandom.com/wiki/Eye_of_the_Storm',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Barbarian_passive_icon.png',
            level: '11',
            activation: 'Passive',
            effects: '<ul><li>Cannot be <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Engaged" class="mw-redirect" title="Engaged">Engaged</a> by enemies more than 1 level below own level</li></ul>',
            speed: '',
            duration: '',
            area: 'Self',
            description: 'The barbarian cannot be Engaged by enemies that are more than 1 level lower than him or her. It does not prevent the barbarian from being attacked in melee.',
        },
        {
            name: 'Heart of Fury',
            link: 'https://pillarsofeternity.fandom.com/wiki/Heart_of_Fury',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/59/Heart_of_fury_icon.png',
            level: '11',
            activation: 'Active (1 per Encounter)',
            effects: '<ul><li><a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Full_Attack" class="mw-redirect" title="Full Attack">Full Attack</a> with +25% <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">damage</a> for 1 second</li></ul>',
            speed: 'Average',
            duration: '1.0 second',
            area: '2.0m Radius from Caster',
            description: 'The barbarian swings viciously in a lightning-quick flurry, taking on all comers. Each equipped weapon attacks every nearby enemy, doing extra damage and inflicting Carnage if applicable.',
        },
        {
            name: 'Barbaric Retaliation',
            link: 'https://pillarsofeternity.fandom.com/wiki/Barbaric_Retaliation',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1e/Barbaric_retaliation_icon.png',
            level: '13',
            activation: 'Passive',
            effects: '<ul><li>Characters hitting Self: 8-12 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage</li></ul>',
            speed: '',
            duration: '',
            area: '',
            description: 'The barbarian reflexively lashes out at anyone who hits him or her in melee, doing Raw damage to anyone unfortunate enough to be on the receiving end.',
        },
        {
            name: 'Dragon Leap',
            link: 'https://pillarsofeternity.fandom.com/wiki/Dragon_Leap',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/fe/Dragon_leap_icon.png',
            level: '13',
            activation: 'Active (1 per Encounter)',
            effects: '<ul><li>Foe AoE: 20-30 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">damage</a></li><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Dazed" class="mw-redirect" title="Dazed">Dazed</a> for 15 seconds</li><li>User: Break <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Engagement" class="mw-redirect" title="Engagement">Engagements</a></li><li>User: Immune to <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Engagement" class="mw-redirect" title="Engagement">Engagement</a> for 2 seconds</li></ul>',
            speed: 'Average',
            duration: '',
            area: '1.5m Radius',
            description: 'Drawing upon reserves of intense spiritual power, barbarians are able to leap high into the air and crash down upon their foes, Dazing them.',
        },
        {
            name: 'Echoing Shout',
            link: 'https://pillarsofeternity.fandom.com/wiki/Echoing_Shout',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/46/Echoing_shout_icon.png',
            level: '15',
            activation: 'Active (1 per Encounter)',
            effects: '<ul><li>Foe Target: 35-50 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">damage</a></li><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Dazed" class="mw-redirect" title="Dazed">Dazed</a> for 6 seconds</li></ul>',
            speed: '',
            duration: '',
            area: 'Length',
            description: 'The barbarian projects his or her rage into a wave of energy that causes Crush damage and Dazes everyone caught in its path. If the shout strikes a solid surface, it will bounce once.',
        },
    ],
    talents: [
        {
            name: 'Accurate Carnage',
            description: 'The barbarian learns to line up his or her most savage blows, improving the Accuracy of secondary attacks from Carnage.',
            effects: '<ul><li>+5 <a href="/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16"></a></li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Accurate_Carnage',
            imageLink: barbarianPassiveImageLink
        },
        {
            name: 'Greater Frenzy',
            requiredAbility: 'Frenzy',
            description: 'Cultivates the barbarian\'s inner rage, granting additional bonuses while under the effects of Frenzy.',
            effects: '<ul><li>+2 <a href="/wiki/Might" title="Might">Might</a></li><li>+2 <a href="/wiki/Constitution" title="Constitution">Constitution</a></li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Greater_Frenzy',
            imageLink: barbarianPassiveImageLink
        },
        {
            name: 'Powerful Sprint',
            requiredAbility: 'Wild Sprint',
            description: 'The barbarian\'s charges become even more ferocious. Speed of Wild Sprint is increased.',
            effects: '<ul><li>+2 <a href="/wiki/Move_Speed" title="Move Speed">Move Speed</a></li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Powerful_Sprint',
            imageLink: barbarianPassiveImageLink
        },
        {
            name: 'Stalwart Defiance',
            requiredAbility: 'Savage Defiance',
            description: 'Strengthens Savage Defiance, causing it to provide a bonus to all defenses.',
            effects: '<ul><li>+10 <a href="/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235317" decoding="async" width="18" height="18"></a></li><li>+10 <a href="/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235327" decoding="async" width="18" height="18"></a></li><li>+10 <a href="/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235341" decoding="async" width="18" height="18"></a></li><li>+10 <a href="/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png/revision/latest/scale-to-width-down/18?cb=20170909202632" decoding="async" width="18" height="18"></a></li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Stalwart_Defiance',
            imageLink: barbarianPassiveImageLink
        },
        {
            name: 'Barbaric Blow',
            description: 'The barbarian deals a massive blow, causing additional Crits and extra damage on Crits. Carnage is not affected.',
            effects: '<ul><li><a href="/wiki/Full_Attack" class="mw-redirect" title="Full Attack">Full Attack</a> (<a href="/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235244" decoding="async" width="16" height="16"></a> vs <a href="/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235317" decoding="async" width="18" height="18"></a>)</li><li>+25% Ability Area of Effect</li><li>+30% of <a href="/wiki/Hit" class="mw-redirect" title="Hit">Hits</a> converted to <a href="/wiki/Crit" class="mw-redirect" title="Crit">Crits</a></li><li>+0.5 to <a href="/wiki/Crit" class="mw-redirect" title="Crit">Crit</a> damage multiplier</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Barbaric_Blow',
            imageLink: barbarianPassiveImageLink
        }
    ]
};
