const chanterPassiveImageLink = 'https://static.wikia.nocookie.net/eternitywiki/images/9/9d/Chanter_passive_icon.png';

export default {
    name: 'Chanter',
    endurancePerLevel: 12,
    healthMultiplier: 4,
    accuracy: 25,
    deflection: 25,
    skillBonuses: {
        'Lore': +2,
        'Mechanics': +1
    },
    baseAbility: {
        name: 'Brisk Recitation',
        link: 'https://pillarsofeternity.fandom.com/wiki/Brisk_Recitation',
        imageLink: chanterPassiveImageLink
    },
    abilities: [
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/And_Hel-Hyraf_Crashed_upon_the_Shield',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/af/Crashed_upon_shield_icon.png',
            name: 'And Hel-Hyraf Crashed upon the Shield',
            effects: '<ul><li>Foe AoE: -5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a></li></ul>',
            speed: 'Average&#160;',
            duration: '12.0 seconds',
            interrupt: '',
            range: '',
            area: 'Length: 5.0m 90В° Cone',
            description: 'Reduces Damage Reduction of enemies in the area of effect.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/But_Reny_Daret%27s_Ghost,_He_Would_not_Rest',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/62/Summon_phantom_icon.png',
            name: 'But Reny Daret\'s Ghost, He Would not Rest',
            effects: '<ul><li>Summon: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Phantom" title="Phantom">Phantom</a></li></ul>',
            speed: 'Average&#160;',
            duration: '12.0 seconds',
            interrupt: '',
            range: '',
            area: '',
            description: 'Calls beyond the Shroud and summons a phantom to fight for the party.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/If_their_Bones_Still_Slept_Under_that_Hill,_None_Can_Say',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/98/Summon_skeletons_icon.png',
            name: 'If their Bones Still Slept Under that Hill, None Can Say',
            effects: '<ul><li>Summon: 3 Human <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Skeleton" title="Skeleton">Skeletons</a></li></ul>',
            speed: 'Average&#160;',
            duration: '20.0 seconds',
            interrupt: '',
            range: '',
            area: '',
            description: 'Summons three skeletons to fight for the party.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Not_Felled_by_the_Axe,_Nor_Broken_by_the_Storm',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/91/Not_felled_icon.png',
            name: 'Not Felled by the Axe, Nor Broken by the Storm',
            effects: '<ul><li>Friendly AoE: +10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a></li><li>Friendly AoE: +5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a></li><li>Caster: +10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a></li><li>Caster: +5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
            speed: 'Average&#160;',
            duration: '20.0 seconds',
            interrupt: '',
            range: '',
            area: 'Length: 2.5m 90В° Cone',
            description: 'Increases the Slash and Shock Damage Reductions for allies in the area of effect.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/The_Thunder_Rolled_like_Waves_on_Black_Seas',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/4d/Thunder_rolled_icon.png',
            name: 'The Thunder Rolled like Waves on Black Seas',
            effects: '<ul><li>Foe Aoe: 12-18 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a></li><li>Foe AoE: 4.0m <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Push?action=edit&amp;redlink=1" class="new" title="Push (page does not exist)">Push</a></li><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a></li></ul>',
            speed: 'Average&#160;',
            duration: '5.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 2.5m 90В° Cone',
            description: 'Creates a thunderous explosion that Stuns and shoves enemies in the area of effect.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Thrice_Was_She_Wronged,_and_Thrice_Justly_Avenged',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/19/Thrice_wronged_icon.png',
            name: 'Thrice Was She Wronged, and Thrice Justly Avenged',
            effects: '<ul><li>Foe AoE: 3x 12-18 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            speed: 'Average&#160;',
            duration: '',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 3.0m 90В° Cone',
            description: 'Drains electrostatic energy from the environment to create three bolts of lightning causing Shock damage to any in their path.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/White_Worms_Writhed_in_the_Bellies_of_the_Dead',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/71/Summon_grubs_icon.png',
            name: 'White Worms Writhed in the Bellies of the Dead',
            effects: '<ul><li>Foe AoE: 20-30 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            speed: 'Average&#160;',
            duration: '',
            interrupt: '',
            range: '',
            area: 'Length 10m 90В° Cone + 2m Radius',
            description: 'Causes a nearby downed enemy to explode, expelling three white grubs and Crushing nearby enemies.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/At_the_Sound_of_His_Voice,_the_Killers_Froze_Stiff',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/4d/At_the_sound_icon.png',
            name: 'At the Sound of His Voice, the Killers Froze Stiff',
            effects: '<ul><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a></li></ul>',
            speed: 'Average&#160;',
            duration: '8.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 5.0m 90В° Cone',
            description: 'Paralyzes enemies in the area of effect.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Gernisc_Slew_the_Beast,_but_Soon_Faced_Its_Kin',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/f1/Summon_wurm_icon.png',
            name: 'Gernisc Slew the Beast, but Soon Faced Its Kin',
            effects: '<ul><li>Summon: 3x <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Wurm" title="Wurm">Wurm</a></li></ul>',
            speed: 'Average&#160;',
            duration: '',
            interrupt: '',
            range: '10m',
            area: '',
            description: 'Conjures three wurms into existence to fight for the party.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/My_Son,_Do_You_See_your_Sisters_Across_the_Moor%3F',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Summon_wisp_icon.png',
            name: 'My Son, Do You See your Sisters Across the Moor?',
            effects: '<ul><li>Summon: 2x <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Will-O%27-Wisp" title="Will-O&#39;-Wisp">Will-O\'-Wisp</a></li></ul>',
            speed: 'Average&#160;',
            duration: '25.0 seconds',
            interrupt: '',
            range: '10m',
            area: '1.0m Radius',
            description: 'Amasses stray soul fragments to form two Will\'O\'Wisps that fight for the party.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Rejoice,_My_Comrades!_Two_Fingers_of_Daylight!',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/92/Rejoice_my_comrades_icon.png',
            name: 'Rejoice, My Comrades! Two Fingers of Daylight!',
            effects: '<ul><li>Friendly Target: +30 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png" decoding="async" width="16" height="16" /></a></li><li>Friendly Target: Immunity: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a></li><li>Caster: +30 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png" decoding="async" width="16" height="16" /></a></li><li>Caster: Immunity: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a></li></ul>',
            speed: 'Fast&#160;',
            duration: '20.0 seconds',
            interrupt: '',
            range: '',
            area: 'Length: 30m, bounces up to 3 times',
            description: 'The chanter creates two bouncing beams of pure light that restore Endurance and grant immunity to Frightened and Terrified on all allies struck by them.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Reny_Daret%27s_Ghost_Spake,_%22I%27ll_Catch_You,_Ben_Fidel%22',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/92/Reny_daret_spake_icon.png',
            name: 'Reny Daret\'s Ghost Spake, &quot;I\'ll Catch You, Ben Fidel&quot;',
            effects: '<ul><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a></li></ul>',
            speed: 'Average&#160;',
            duration: '12.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 5.0m 90В° Cone',
            description: 'Causes enemies in the area of effect to be Terrified.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Shatter_their_Shackles,_Cast_off_their_Chains!',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/ad/Shatter_shackle_icon.png',
            name: 'Shatter their Shackles, Cast off their Chains!',
            effects: '<ul><li>Friendly AoE: +25 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> on <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Disengagement" class="mw-redirect" title="Disengagement">Disengagement</a></li><li>Friendly AoE: +50 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Petrified" class="mw-redirect" title="Petrified">Petrified</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Stuck" class="mw-redirect" title="Stuck">Stuck</a> attacks</li><li>Friendly AoE: -10 seconds <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Petrified" class="mw-redirect" title="Petrified">Petrified</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Stuck" class="mw-redirect" title="Stuck">Stuck</a> duration</li><li>Caster: +25 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> on <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Disengagement" class="mw-redirect" title="Disengagement">Disengagement</a></li><li>Caster: +50 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Petrified" class="mw-redirect" title="Petrified">Petrified</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Stuck" class="mw-redirect" title="Stuck">Stuck</a> attacks</li><li>Caster: -10 seconds <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Petrified" class="mw-redirect" title="Petrified">Petrified</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Stuck" class="mw-redirect" title="Stuck">Stuck</a> duration</li></ul>',
            speed: 'Average&#160;',
            duration: '20.0 seconds',
            interrupt: '',
            range: '',
            area: 'Length: 5.0m 90В° Cone',
            description: 'Decreases the duration of and defends against Hobbled, Stuck, Paralyzed, and Petrified effects for allies in the area of effect.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/The_Lover_Cried_out_to_the_Beloved,_%22I_am_Yours!%22',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/0d/The_lover_cried_icon.png',
            name: 'The Lover Cried out to the Beloved, &quot;I am Yours!&quot;',
            effects: '<ul><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Charmed" class="mw-redirect" title="Charmed">Charmed</a></li></ul>',
            speed: 'Average&#160;',
            duration: '8.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 2.5m 90В° Cone',
            description: 'Stirs something deep inside enemies in the area of effect, Charming them.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Gernisc%27s_Beast_Lit_the_Night_with_his_Breath',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/9d/Summon_drake_icon.png',
            name: 'Gernisc\'s Beast Lit the Night with his Breath',
            effects: '<ul><li>Summon: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Drake" title="Drake">Drake</a></li></ul>',
            speed: 'Average&#160;',
            duration: '30.0 seconds',
            interrupt: '',
            range: '10m',
            area: '1.0m Radius',
            description: 'Calls down a drake from the skies to fight for the party.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Oh,_But_Knock_Not_on_the_Door_of_Urdel_and_Gurdel',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e7/Summon_ogre_icon.png',
            name: 'Oh, But Knock Not on the Door of Urdel and Gurdel',
            effects: '<ul><li>Summon: 2x <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Ogre" title="Ogre">Ogre</a></li></ul>',
            speed: 'Average&#160;',
            duration: '30.0 seconds',
            interrupt: '',
            range: '10m',
            area: '1.0m Radius',
            description: 'Summons two fearsome ogres to fight for the party for the duration.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Rise_Again,_Rise_Again,_Scions_of_Adon!',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/84/Rise_again_scions_icon.png',
            name: 'Rise Again, Rise Again, Scions of Adon!',
            effects: '<ul><li>Friendly AoE: Revive with 50 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png" decoding="async" width="16" height="16" /></a></li></ul>',
            speed: 'Average&#160;',
            duration: '',
            interrupt: '',
            range: '',
            area: 'Length: 3.5m 90В° Cone',
            description: 'Revives allies in the area of effect with a small amount of Endurance.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Seven_Nights_She_Waited_While_the_White_Winds_Wept',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/c/ca/Seven_nights_icon.png',
            name: 'Seven Nights She Waited While the White Winds Wept',
            effects: '<ul><li>7x bolts doing 45-60 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            speed: 'Average&#160;',
            duration: '',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 7.5m',
            description: 'Attacks enemies in seven directions around the chanter with bolts of freezing ice.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/The_Bride_Caught_their_Ruse_and_Set_to_Make_them_Pay',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/12/Bride_caught_icon.png',
            name: 'The Bride Caught their Ruse and Set to Make them Pay',
            effects: '<ul><li>Friendly AoE: +5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Dexterity" title="Dexterity">Dexterity</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Perception" title="Perception">Perception</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Intellect" title="Intellect">Intellect</a></li><li>Caster: +5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Dexterity" title="Dexterity">Dexterity</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Perception" title="Perception">Perception</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Intellect" title="Intellect">Intellect</a></li></ul>',
            speed: 'Average&#160;',
            duration: '30.0 seconds',
            interrupt: '',
            range: '',
            area: 'Length: 3.0m 90В° Cone',
            description: 'Empowers allies in the area of effect with bonuses to Dexterity, Perception, and Intellect.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/The_Brideman_Slew_Thirty_%27Fore_they_Crossed_Half_the_Hall',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Brideman_slew_icon.png',
            name: 'The Brideman Slew Thirty \'Fore they Crossed Half the Hall',
            effects: '<ul><li>Friendly AoE: +5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Constitution" title="Constitution">Constitution</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Might" title="Might">Might</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Resolve" title="Resolve">Resolve</a></li><li>Caster: +5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Constitution" title="Constitution">Constitution</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Might" title="Might">Might</a>, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Resolve" title="Resolve">Resolve</a></li></ul>',
            speed: 'Average&#160;',
            duration: '30.0 seconds',
            interrupt: '',
            range: '',
            area: 'Length: 3.0m 90В° Cone',
            description: 'Empowers allies in the area of effect with bonuses to Might, Constitution and Resolve.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/So_Singt_thy_Biting_Winds_o%27_Eld_Nary',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/43/So_singt_thy_biting_winds_o_eld_nary_icon.png',
            name: 'So Singt thy Biting Winds o\' Eld Nary',
            effects: '<ul><li>Foe Target: 40-50 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png" decoding="async" width="18" height="18" /></a> damage, +25% <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> damage, 15 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> bypass, -2 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Move_Speed" title="Move Speed">Move Speed</a></li><li>Foe Jump Target (x4): 40-50 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png" decoding="async" width="18" height="18" /></a> damage, +25% <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> damage, 15 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> bypass, -2 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Move_Speed" title="Move Speed">Move Speed</a></li></ul>',
            speed: 'Average&#160;',
            duration: '8.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '10m +5m Jump',
            area: 'Foe Target +4 Foe Jump Targets',
            description: 'Devastates enemies with a powerful blast of cold air that inflicts Freeze damage (ignoring a large amount of DR) and slows movement.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/Their_Champion_Braved_The_Horde_Alone',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/ad/The_champion_braved_the_horde_alone_icon.png',
            name: 'Their Champion Braved The Horde Alone',
            effects: '<ul><li>+40% <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Attack_Speed" title="Attack Speed">Attack Speed</a></li><li>+10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a></li><li>+50 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Interrupt" class="mw-redirect" title="Interrupt">Interrupt</a></li></ul>',
            speed: 'Average&#160;',
            duration: '30.0 seconds',
            interrupt: '',
            range: '',
            area: 'Self',
            description: 'The chanter fills himself or herself with frantic energy, significantly increasing Attack Speed.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/What_Rou_Naka_Found_Down_the_Deep',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/ee/What_rou_naka_found_icon.png',
            name: 'What Rou Naka Found Down the Deep',
            effects: '<ul><li>Summon: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Swamp_Spore" title="Swamp Spore">Swamp Spore</a></li></ul>',
            speed: 'Average&#160;',
            duration: '35.0 seconds',
            interrupt: '',
            range: '10m',
            area: '',
            description: 'Summons a swamp spore to fight for the chanter.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Boil_Their_Flesh_From_Skin_to_Bone',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/2b/Boil_their_flesh_icon.png',
            name: 'Boil Their Flesh From Skin to Bone',
            effects: '<ul><li>Foe AoE: 30-45 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png" decoding="async" width="18" height="18" /></a>, Destroyed (<a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>AoE: 30-42 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png" decoding="async" width="18" height="18" /></a> damage, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a> (<a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average&#160;',
            duration: '10.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 3.0m 90В° Cone',
            description: 'This ghastly invocation causes victims\' bodies and souls to rapidly dissolve, doing Raw damage to enemies caught in its path.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Called_to_His_Bidding,_the_Ancient_Instruments_of_Death',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/dc/Called_to_his_bidding_icon.png',
            name: 'Called to His Bidding, the Ancient Instruments of Death',
            effects: '<ul><li>Summon: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Animated_Great_Sword?action=edit&amp;redlink=1" class="new" title="Animated Great Sword (page does not exist)">Animated Great Sword</a></li><li>Summon: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Animated_Pike?action=edit&amp;redlink=1" class="new" title="Animated Pike (page does not exist)">Animated Pike</a></li><li>Summon: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Animated_War_Bow?action=edit&amp;redlink=1" class="new" title="Animated War Bow (page does not exist)">Animated War Bow</a></li></ul>',
            speed: 'Average&#160;',
            duration: '45.0 seconds',
            interrupt: '',
            range: '10m',
            area: '',
            description: 'The chanter summons a collection of ancient weapons to attack his or her foes.',
        },
    ],
    phrases: [
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/At_the_Sight_of_their_Comrades,_their_Hearts_Grew_Bold',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/72/Heart_grew_bold_icon.png',
            name: 'At the Sight of their Comrades, their Hearts Grew Bold',
            area: 'Friendly Aura',
            effects: '<ul><li>+10 <a target="_blank" href="/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a></li><li>+10 <a target="_blank" href="/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
            duration: '4.0 seconds',
            linger: '2.0 seconds',
            description: 'Emboldens allies in the area of effect, giving bonuses to Fortitude and Will.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Blessed_Was_Wengridh,_Quickest_of_His_Tribe',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/9a/Blessed_was_icon.png',
            name: 'Blessed Was Wengridh, Quickest of His Tribe',
            area: 'Friendly Aura',
            effects: '<ul><li>+1.2 <a target="_blank" href="/wiki/Move_Speed" title="Move Speed">Move Speed</a></li><li>+10 <a target="_blank" href="/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
            duration: '4.0 seconds',
            linger: '2.0 seconds',
            description: 'Increases the movement rate and Reflex of all allies in the area of effect.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Come,_Come_Soft_Winds_of_Death',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/0e/Winds_of_death_icon.png',
            name: 'Come, Come Soft Winds of Death',
            area: 'Foe Aura',
            effects: '<ul><li>-2 <a target="_blank" href="/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> per 3 seconds</li></ul>',
            duration: '4.0 seconds',
            linger: '2.0 seconds',
            description: 'Drains a portion of Endurance from all enemies in the area of effect.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Dull_the_Edge,_Blunt_the_Point',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8e/Dull_the_edge_icon.png',
            name: 'Dull the Edge, Blunt the Point',
            area: 'Foe Aura',
            effects: '<ul><li>-10% <a target="_blank" href="/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>-10% <a target="_blank" href="/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            duration: '4.0 seconds',
            linger: '2.0 seconds',
            description: 'Reduces Slashing and Piercing damage of enemies in the area of effect.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Thick_Grew_Their_Tongues,_Stumbling_O%27er_Words',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/fb/Tongue_tied_icon.png',
            name: 'Thick Grew Their Tongues, Stumbling O\'er Words',
            area: 'Foe Aura',
            effects: '<ul><li>-10 <a target="_blank" href="/wiki/Concentration" class="mw-redirect" title="Concentration">Concentration</a></li></ul>',
            duration: '4.0 seconds',
            linger: '2.0 seconds',
            description: 'Reduces Concentration of enemies in the area of effect.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Lo,_Their_Endless_Host,_the_Harbingers_Doom',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/07/Endless_host_icon.png',
            name: 'Lo, Their Endless Host, the Harbingers Doom',
            area: 'Foe Aura',
            effects: '<ul><li><a target="_blank" href="/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a></li></ul>',
            duration: '6.0 seconds',
            linger: '3.0 seconds',
            description: 'Generates a field of terror, Frightening enemies in the area of effect.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/One_Dozen_Stood_Against_the_Power_of_the_Saint',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/3e/One_dozen_stood_icon.png',
            name: 'One Dozen Stood Against the Power of the Saint',
            area: 'Friendly Aura',
            effects: '<ul><li>+25 <a target="_blank" href="/wiki/Defense" title="Defense">Defense</a> vs <a target="_blank" href="/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a></li><li>-10 seconds <a target="_blank" href="/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a> duration</li><li>+15 <a target="_blank" href="/wiki/Defense" title="Defense">Defense</a> vs <a target="_blank" href="/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a></li><li>-5 seconds <a target="_blank" href="/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a> duration</li></ul>',
            duration: '6.0 seconds',
            linger: '3.0 seconds',
            description: 'Decreases the duration of and defends against Frightened and Terrified effects for allies in the area of effect.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Rime_and_Frost_Followed_the_Footfalls_of_Karth',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/5c/Rime_and_frost_icon.png',
            name: 'Rime and Frost Followed the Footfalls of Karth',
            area: 'Friendly Aura',
            effects: '<ul><li>Drop Trap: Rime and Frost Trap per 3 seconds</li><li>Trap causes <a target="_blank" href="/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a> for 10 seconds</li></ul>',
            duration: '6.0 seconds',
            linger: '3.0 seconds',
            description: 'Allies leave a hazardous trail of frost wherever they move, Hobbling and causing Freeze damage to enemies.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Sure-Handed_Ila_Nocked_Her_Arrows_with_Speed',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/46/Sure_handed_ila_icon.png',
            name: 'Sure-Handed Ila Nocked Her Arrows with Speed',
            area: 'Friendly Aura',
            effects: '<ul><li>+20% <a target="_blank" href="/wiki/Reload_Speed?action=edit&amp;redlink=1" class="new" title="Reload Speed (page does not exist)">Reload Speed</a></li><li>+20% Ranged <a target="_blank" href="/wiki/Attack_Speed" title="Attack Speed">Attack Speed</a></li></ul>',
            duration: '6.0 seconds',
            linger: '3.0 seconds',
            description: 'Decreases reload time and increases the speed of ranged attacks for all allies.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/The_Fox_from_the_Farmer_Did_Run_and_Leap',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1d/Fox_leap_icon.png',
            name: 'The Fox from the Farmer Did Run and Leap',
            area: 'Foe Aura',
            effects: '<ul><li>-10 <a target="_blank" href="/wiki/Accuracy" title="Accuracy">Accuracy</a> on <a target="_blank" href="/wiki/Disengagement" class="mw-redirect" title="Disengagement">Disengagement</a> attacks</li></ul>',
            duration: '6.0 seconds',
            linger: '3.0 seconds',
            description: 'Reduces Accuracy of Disengagement Attacks for enemies in the area of effect.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Aefyllath_Ues_Mith_Fyr',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/0b/Mith_fyr_icon.png',
            name: 'Aefyllath Ues Mith Fyr',
            area: 'Friendly Aura',
            effects: '<ul><li>+25% <a target="_blank" href="/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            duration: '8.0 seconds',
            linger: '4.0 seconds',
            description: 'Bestows a Burning effect on all ally weapons.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Seven_Men,_Onto_the_Deck_They_Went',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/2a/Seven_men_icon.png',
            name: 'Seven Men, Onto the Deck They Went',
            area: 'Friendly Aura',
            effects: '<ul><li>+15 <a target="_blank" href="/wiki/Defense" title="Defense">Defense</a> vs <a target="_blank" href="/wiki/Prone" class="mw-redirect" title="Prone">Prone</a> attacks</li><li>+15 <a target="_blank" href="/wiki/Concentration" class="mw-redirect" title="Concentration">Concentration</a></li><li>+10 <a target="_blank" href="/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png" decoding="async" width="18" height="18" /></a></li><li>+10 <a target="_blank" href="/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
            duration: '8.0 seconds',
            linger: '4.0 seconds',
            description: 'Allies in the area of effect gain a bonus to Freeze and Shock Damage Reductions, and a bonus to defense against the Prone affliction.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/The_Dragon_Thrashed,_The_Dragon_Wailed',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/41/Dragon_thrashed_icon.png',
            name: 'The Dragon Thrashed, The Dragon Wailed',
            area: 'Foe Aura',
            effects: '<ul><li>10 <a target="_blank" href="/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage per 3 seconds</li><li>10 <a target="_blank" href="/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a> damage per 3 seconds</li></ul>',
            duration: '8.0 seconds',
            linger: '4.0 seconds',
            description: 'Generates a hazard field causing Burn and Slash damage to enemies in the area of effect.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/The_Silver_Knights%27_Shields_Broke_Both_Arrow_and_Blade',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d4/Silver_shield_icon.png',
            name: 'The Silver Knights\' Shields Broke Both Arrow and Blade',
            area: 'Friendly Aura',
            effects: '<ul><li>+10 <a target="_blank" href="/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a></li></ul>',
            duration: '8.0 seconds',
            linger: '4.0 seconds',
            description: 'Increases the Deflection of allies in the area of effect.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/Her_Courage_Thick_as_Steel',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/df/Her_courage_thick_as_steel_icon.png',
            name: 'Her Courage Thick as Steel',
            area: 'Friendly Aura',
            effects: '<ul><li>30-pt Damage Shield</li></ul>',
            duration: '10.0 seconds',
            linger: '5.0 seconds',
            description: 'Provides a barrier that soaks up damage against the chanter\'s allies.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/Old_Siec_Would_Not_Rest_%27til_His_Hunger_Was_Sated',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/84/Old_siec_would_not_rest_icon.png',
            name: 'Old Siec Would Not Rest \'til His Hunger Was Sated',
            area: 'Friendly Aura',
            effects: '<ul><li>15% of <a target="_blank" href="/wiki/Damage" class="mw-redirect" title="Damage">Damage</a> is restored as <a target="_blank" href="/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a></li></ul>',
            duration: '10.0 seconds',
            linger: '5.0 seconds',
            description: 'The chanter\'s allies regain a portion of damage they inflict as Endurance.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/They_Shielded_Their_Eyes_%27Gainst_the_Fampyr%27s_Gaze',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1e/They_shielded_their_eyes_icon.png',
            name: 'They Shielded Their Eyes \'Gainst the Fampyr\'s Gaze',
            area: 'Friendly Aura',
            effects: '<ul><li>+20 <a target="_blank" href="/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Confused" class="mw-redirect" title="Confused">Confused</a> attacks</li><li>+20 <a target="_blank" href="/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Charmed" class="mw-redirect" title="Charmed">Charmed</a> attacks</li><li>+20 <a target="_blank" href="/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Dominated" class="mw-redirect" title="Dominated">Dominated</a> attacks</li><li>+20 <a target="_blank" href="/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
            duration: '10.0 seconds',
            linger: '5.0 seconds',
            description: 'The chanter\'s allies gain a bonus to their Will defense and to resist Charmed, Confused, Dominated afflictions.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Mercy_and_Kindness_Followed_Where%27er_She_Walked',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Mercy_and_kindness_icon.png',
            name: 'Mercy and Kindness Followed Where\'er She Walked',
            area: 'Friendly Aura',
            effects: '<ul><li>+100% <a target="_blank" href="/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png" decoding="async" width="16" height="16" /></a> received</li></ul>',
            duration: '12.0 seconds',
            linger: '6.0 seconds',
            description: 'All allies receive more Endurance from healing effects.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/With_All_Your_Strength_Slay_the_Beast',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d2/With_all_your_strength_icon.png',
            name: 'With All Your Strength Slay the Beast',
            area: 'Friendly Aura',
            effects: '<ul><li>+20 <a target="_blank" href="/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="/wiki/Beasts" class="mw-redirect" title="Beasts">Beasts</a></li><li>+30% <a target="_blank" href="/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png" decoding="async" width="18" height="18" /></a> vs <a target="_blank" href="/wiki/Beasts" class="mw-redirect" title="Beasts">Beasts</a></li></ul>',
            duration: '12.0 seconds',
            linger: '6.0 seconds',
            description: 'The chanter increases allies\' Accuracy and Damage against all enemies of the Beast type.',
        },
    ],
    talents: [
        {
            name: 'Ancient Memory',
            description: 'Invokes a primal energy, causing allies within range to benefit from constant Endurance regeneration while the Chanter is chanting.',
            effects: '<ul><li>Allied AoE: +2 <a href="/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235322" decoding="async" width="16" height="16"></a> (base) +0.7 every 3 levels after 1</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Ancient_Memory',
            imageLink: chanterPassiveImageLink
        },
        {
            name: 'Beloved Spirits',
            description: 'Improves the chanter\'s connection to the soul fragments they employ, increasing Ancient Memory\'s healing capability.',
            effects: '<ul><li>Allied AoE: +0.8 <a href="/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235322" decoding="async" width="16" height="16"></a> (base) +0.4 every 3 levels after 1</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Beloved_Spirits',
            imageLink: chanterPassiveImageLink,
            requiredTalent: 'Ancient Memory'
        }
    ],
};
