const cipherPassiveImageLink = 'https://static.wikia.nocookie.net/eternitywiki/images/3/3f/Cipher_passive_icon.png';

export default {
    name: 'Cipher',
    endurancePerLevel: 12,
    healthMultiplier: 4,
    accuracy: 25,
    deflection: 20,
    skillBonuses: {
        Stealth: +1,
        Lore: +1,
        Mechanics: +1
    },
    baseAbility: {
        name: 'Soul Whip',
        link: 'https://pillarsofeternity.fandom.com/wiki/Soul_Whip',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/77/Soul_whip_icon.png'
    },
    abilities: [
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Antipathetic_Field',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/3c/Antipathetic_field_icon.png',
            name: 'Antipathetic Field',
            focus: '10&#160;',
            effects: '<ul><li>Beam: 13-20 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png" decoding="async" width="18" height="18" /></a> damage per second</li><li>User: +20% Beam Damage over 12 seconds</li></ul>',
            speed: 'Average',
            duration: '6.0 seconds',
            range: '15m',
            area: 'Beam',
            description: 'Creates a toxic physical manifestation of the mutual antipathy between the cipher and the enemy target. Enemies caught in the path between the two will suffer Corrosive damage.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Eyestrike',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/fe/Eyestrike_icon.png',
            name: 'Eyestrike',
            focus: '10&#160;',
            effects: '<ul><li>Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Blinded" class="mw-redirect" title="Blinded">Blinded</a> and <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Dazed" class="mw-redirect" title="Dazed">Dazed</a> (+10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Blinded" class="mw-redirect" title="Blinded">Blinded</a> (+5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '10.0 seconds',
            range: '10m',
            area: 'Target + 1.5m Radius',
            description: 'Shocks an enemy\'s visual receptors, Dazing and Blinding them as well as Blinding nearby targets.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Mind_Wave',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/39/Mind_wave_icon.png',
            name: 'Mind Wave',
            focus: '10&#160;',
            effects: '<ul><li>Target: 10-18 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png" decoding="async" width="18" height="18" /></a> (+10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Prone" class="mw-redirect" title="Prone">Prone</a> (+5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Fast',
            duration: '3.0 seconds',
            range: '8m',
            area: 'Target + Length: 3.5m 120В° Cone',
            description: 'Target becomes the object of a concussive blast of psychic energy, suffering Raw damage from the trauma. Characters in a conical area behind the target failing a Fortitude check are knocked prone from the blast.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Soul_Shock',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/12/Soul_shock_icon.png',
            name: 'Soul Shock',
            focus: '10&#160;',
            effects: '<ul><li>22-30 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            speed: 'Average',
            duration: '',
            range: '6m',
            area: 'Allied Target + 1.75m Radius',
            description: 'Briefly transforms the outer shell of an allied target\'s soul into energy, releasing an electrical burst around them. Characters standing in the area around the target take Shock damage.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Tenuous_Grasp',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/02/Tenuous_grasp_icon.png',
            name: 'Tenuous Grasp',
            focus: '10&#160;',
            effects: '<ul><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a> for 15 seconds</li><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Confused" class="mw-redirect" title="Confused">Confused</a> for 6 seconds</li></ul>',
            speed: 'Average',
            duration: '',
            range: '10m',
            area: 'Foe Target',
            description: 'Assails the target\'s grasp on reality, Frightening and Confusing them.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Whisper_of_Treason',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/5b/Whisper_of_treason_icon.png',
            name: 'Whisper of Treason',
            focus: '10&#160;',
            effects: '<ul><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Charmed" class="mw-redirect" title="Charmed">Charmed</a></li></ul>',
            speed: 'Fast',
            duration: '10.0 seconds',
            range: '7m',
            area: 'Foe Target',
            description: 'Imparts a bedeviling secret to an enemy that causes its allegiance to bend, Charming them for the duration.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Amplified_Thrust',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/f5/Amplified_thrust_icon.png',
            name: 'Amplified Thrust',
            focus: '20&#160;',
            effects: '<ul><li>Foe Target: 40-55 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>Foe Target: 3.0m Push</li></ul>',
            speed: 'Fast',
            duration: '',
            range: '5m + 3m Jump',
            area: 'Allied Target + 1 Foe Jump Target',
            description: 'Bounces psychic energy harmlessly off the target and onto the closest nearby enemy, causing Pierce damage and violently pushing them backward.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Mental_Binding',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/36/Mental_binding_icon.png',
            name: 'Mental Binding',
            focus: '20&#160;',
            effects: '<ul><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a> for 8.0 seconds (+10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Stuck" class="mw-redirect" title="Stuck">Stuck</a> for 6.0 seconds (+5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '',
            range: '8m',
            area: 'Foe Target + 2.0m Radius',
            description: 'Overwhelms the target\'s mental ability to communicate with its own body, Paralyzing it and causing its soul to emit a shockwave that can leave nearby enemies Stuck.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Mind_Blades',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/61/Mind_blades_icon.png',
            name: 'Mind Blades',
            focus: '20&#160;',
            effects: '<ul><li>Foe Target: 18-28 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>Foe Jump Targets (x5): 16-25 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            speed: 'Average',
            duration: '',
            range: '10m + 10m Jump',
            area: 'Foe Target + 5 Jump Targets',
            description: 'Co-opts the target\'s essence, generating a Slashing blade of force that attacks them before leaping to up to five additional targets.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Phantom_Foes',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/40/Phantom_foes_icon.png',
            name: 'Phantom Foes',
            focus: '20&#160;',
            effects: '<ul><li>Foe AoE: -10 enemies needed to <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Flank" class="mw-redirect" title="Flank">Flank</a> for 20.0 seconds</li><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a> for 6.0 seconds</li></ul>',
            speed: 'Average',
            duration: '',
            range: '10m',
            area: 'Foe Target + 5.0m Radius',
            description: 'Invades the minds of targets in the area of effect, causing them to believe they are surrounded by phantom foes - leaving them Flanked for the duration.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Psychovampiric_Shield',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1a/Psychovampiric_shield_icon.png',
            name: 'Psychovampiric Shield',
            focus: '20&#160;',
            effects: '<ul><li>Drains -10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Resolve" title="Resolve">Resolve</a> for +25 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a></li></ul>',
            speed: 'Average',
            duration: '20.0 seconds',
            range: '8m',
            area: '',
            description: 'The cipher uses the target\'s strength of mind against it, stealing a portion of its Resolve in order to better Deflect incoming attacks.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Recall_Agony',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Recall_agony_icon.png',
            name: 'Recall Agony',
            focus: '20&#160;',
            effects: '<ul><li>30% of all <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">damage</a> reapplied</li></ul>',
            speed: 'Fast',
            duration: '12.0 seconds',
            range: '8m',
            area: 'Foe Target',
            description: 'Causes the target to relive the psychic trauma of an injury moments after receiving it, experiencing the Damage all over again.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Ectopsychic_Echo',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/a2/Ectopsychic_echo_icon.png',
            name: 'Ectopsychic Echo',
            focus: '30&#160;',
            effects: '<ul><li>Foe Beam: 20-30 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> damage per second</li></ul>',
            speed: 'Average',
            duration: '10.0 seconds',
            range: '12m',
            area: 'Foe Beam',
            description: 'Generates a rebounding wave of psychic feedback between the cipher and an ally that causes Crush damage to enemies caught in between.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Fractured_Volition',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/2f/Fractured_volition_icon.png',
            name: 'Fractured Volition',
            focus: '30&#160;',
            effects: '<ul><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a></li><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a></li></ul>',
            speed: 'Average',
            duration: '12.0 seconds',
            range: '10m',
            area: 'Foe Target',
            description: 'Violates an enemy\'s memories to bring vivid recollections of past failures to the surface, leaving the target Hobbled and Weakened.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Pain_Link',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/98/Pain_link_icon.png',
            name: 'Pain Link',
            focus: '30&#160;',
            effects: '<ul><li>Allied Target: 25% of all <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">damage</a> reapplied to nearby enemies</li></ul>',
            speed: 'Average',
            duration: '18.0 seconds',
            range: '8m',
            area: 'Allied Target',
            description: 'Mentally links nearby enemies to the target, forcing them to experience a portion of all Damage the target suffers.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Puppet_Master',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e1/Puppet_master_icon.png',
            name: 'Puppet Master',
            focus: '30&#160;',
            effects: '<ul><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Dominated" class="mw-redirect" title="Dominated">Dominated</a></li></ul>',
            speed: 'Fast',
            duration: '16.0 seconds',
            range: '5m',
            area: 'Foe Target',
            description: 'Destroys a target\'s psychic defenses, leaving them Dominated by the cipher for the duration.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Secret_Horrors',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/9d/Secret_horrors_icon.png',
            name: 'Secret Horrors',
            focus: '30&#160;',
            effects: '<ul><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a></li><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a></li></ul>',
            speed: 'Average',
            duration: '15.0 seconds',
            range: '10m',
            area: 'Foe Target + 3.0m Radius',
            description: 'Causes enemies in the area of effect to believe their worst fears have been realized, Frightening and Sickening them for the duration.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Soul_Ignition',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/82/Soul_ignition_icon.png',
            name: 'Soul Ignition',
            focus: '30&#160;',
            effects: '<ul><li>Foe Target: 95.3 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            speed: 'Average',
            duration: '10.0 seconds',
            range: '10m',
            area: 'Foe Target',
            description: 'Forces an enemy\'s soul to "leak" energy, igniting the air around them and Burning them over time.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Body_Attunement',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Body_attunement_icon.png',
            name: 'Body Attunement',
            focus: '40&#160;',
            effects: '<ul><li>Foe Target: 7.0 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> stolen</li></ul>',
            speed: 'Fast',
            duration: '15.0 seconds',
            range: '10m',
            area: 'Foe Target',
            description: 'The cipher probes the mind and soul of the enemy target, finding the strengths of its defenses and stealing them for his or her own. Drains a portion of the target\'s Damage Reduction, granting the same amount as a bonus to the cipher.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Going_Between',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/21/Going_between_icon.png',
            name: 'Going Between',
            focus: '40&#160;',
            effects: '<ul><li>+25% of incoming <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Crit" class="mw-redirect" title="Crit">Crits</a> converted to <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Hit" class="mw-redirect" title="Hit">Hits</a></li><li>+25% of incoming <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Hit" class="mw-redirect" title="Hit">Hits</a> converted to <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Graze" class="mw-redirect" title="Graze">Grazes</a></li><li>+25% of incoming <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Graze" class="mw-redirect" title="Graze">Grazes</a> converted to <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Miss" class="mw-redirect" title="Miss">Misses</a></li><li>+3 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Move_Speed" title="Move Speed">Move Speed</a></li></ul>',
            speed: 'Fast',
            duration: '30.0 seconds',
            range: '10m',
            area: 'Allied Target',
            description: 'An ally superficially takes on the form of a spirit. Their movement is increased and many incoming Crits, Hits, and Grazes are converted to a less severe result.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Mind_Lance',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/32/Mind_lance_icon.png',
            name: 'Mind Lance',
            focus: '40&#160;',
            effects: '<ul><li>35-42 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage to anyone in the line of attack</li></ul>',
            speed: 'Fast',
            duration: '',
            range: '',
            area: 'Target + Length: 10m',
            description: 'Impales the target with a lance of pure force, inflicting major Pierce damage to anyone in the line of attack with a high chance of causing an Interrupt.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Pain_Block',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/25/Pain_block_icon.png',
            name: 'Pain Block',
            focus: '40&#160;',
            effects: '<ul><li>Allied Target: +10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a></li><li>Allied Target: +76.7 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a></li></ul>',
            speed: 'Average',
            duration: '20.0 seconds',
            range: '10m',
            area: 'Allied Target',
            description: 'Provides an ally with a mental block on his or her pain, granting a bonus to their Damage Reduction and regenerating Endurance over time.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Silent_Scream',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/60/Silent_scream_icon.png',
            name: 'Silent Scream',
            focus: '40&#160;',
            effects: '<ul><li>Foe Target: 35-50 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a> (+10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe AoE: 28-40 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage (+5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '8.0 seconds',
            range: '6m',
            area: 'Target + 2.5m Radius',
            description: 'Produces a psychic howl in the targeted area, Stunning the target as well as dealing Raw damage to all enemies within. Stands a high chance of causing an Interrupt.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Wild_Leech',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/9a/Wild_leech_icon.png',
            name: 'Wild Leech',
            focus: '40&#160;',
            effects: '<ul><li>10 points stolen from a random <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Attribute" class="mw-redirect" title="Attribute">attribute</a></li></ul>',
            speed: 'Average',
            duration: '15.0 seconds',
            range: '10m',
            area: 'Target',
            description: 'Latches onto some characteristic of the target\'s psyche and drains it, granting the same amount as a bonus to the cipher. Affects a random Attribute.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Borrowed_Instinct',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/80/Borrowed_instinct_icon.png',
            name: 'Borrowed Instinct',
            focus: '50&#160;',
            effects: '<ul><li>Foe Target: -8 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Intellect" title="Intellect">Intellect</a>, -8 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Perception" title="Perception">Perception</a></li><li>User: +20 Melee <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a>, +20 Ranged <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a>, +20 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png" decoding="async" width="18" height="18" /></a>, +20 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>, +20 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>, +20 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
            speed: 'Average',
            duration: '25.0 seconds',
            range: '10m',
            area: 'Foe Target',
            description: 'Ransacks an enemy\'s Intellect and Perception for energy, causing damage to those enemy Attributes while boosting the cipher\'s Defenses and Accuracy.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Detonate',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/7a/Detonate_icon.png',
            name: 'Detonate',
            focus: '50&#160;',
            effects: '<ul><li>50-75 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage</li><li>Destroyed, 2.0m Push</li></ul>',
            speed: 'Average',
            duration: '',
            range: '5m',
            area: 'Target',
            description: 'Splinters the target\'s soul with sheer force, inflicting Raw damage to them - targets with low Endurance explode, causing Crush damage to all in the area of effect.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Ringleader',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/c/cd/Ringleader_icon.png',
            name: 'Ringleader',
            focus: '50&#160;',
            effects: '<ul><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Dominated" class="mw-redirect" title="Dominated">Dominated</a> (+10 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe AoE: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Charmed" class="mw-redirect" title="Charmed">Charmed</a> (+5 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Slow',
            duration: '10.0 seconds',
            range: '4m',
            area: 'Foe Target + 1.5m Radius',
            description: 'Imprints an insidious and powerful compulsion to obey the cipher across all enemies in the area of effect, Dominating the target and Charming all others.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Tactical_Meld',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/b/b3/Tactical_meld_icon.png',
            name: 'Tactical Meld',
            focus: '50&#160;',
            effects: '<ul><li>User: +20 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> when attacking the same enemy as the target</li></ul>',
            speed: 'Fast',
            duration: '25.0 seconds',
            range: '5m',
            area: 'Allied Target',
            description: 'Connects the mind of the cipher with an ally to gain the ally\'s knowledge of his or her enemy, bestowing an attack bonus upon the cipher towards the enemy the ally is attacking.',
        },
        {
            level: '11',
            link: 'https://pillarsofeternity.fandom.com/wiki/Amplified_Wave',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/6d/Amplified_wave_icon.png',
            name: 'Amplified Wave',
            focus: '60&#160;',
            effects: '<ul><li>Foe AoE: 35-42 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> damage, <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Prone" class="mw-redirect" title="Prone">Prone</a></li></ul>',
            speed: 'Fast',
            duration: '8.0 seconds',
            range: '6m',
            area: 'Allied Target + 4.0m Radius',
            description: 'Manifests the target ally\'s mental strengths and projects them outward forcefully, causing a shockwave that inflicts Crush damage and knocks any in the area of effect Prone.',
        },
        {
            level: '11',
            link: 'https://pillarsofeternity.fandom.com/wiki/Disintegration',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/39/Disintegration_icon.png',
            name: 'Disintegration',
            focus: '60&#160;',
            effects: '<ul><li>240 <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage over time</li></ul>',
            speed: 'Average',
            duration: '15.0 seconds',
            range: '10m',
            area: 'Foe Target',
            description: 'Burns away the ethereal sinew that holds together the mind, body, and soul of the target enemy, causing it to rapidly take Raw damage. Targets that have their Endurance reduced to zero disintegrate into nonexistence.',
        },
        {
            level: '11',
            link: 'https://pillarsofeternity.fandom.com/wiki/Mind_Plague',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1c/Mind_plague_icon.png',
            name: 'Mind Plague',
            focus: '60&#160;',
            effects: '<ul><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Dazed" class="mw-redirect" title="Dazed">Dazed</a> for 12 seconds</li><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Confused" class="mw-redirect" title="Confused">Confused</a> for 5 seconds</li><li>Foe Jump Targets (x5): <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Dazed" class="mw-redirect" title="Dazed">Dazed</a> for 12 seconds</li><li>Foe Jump Targets (x5): <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Confused" class="mw-redirect" title="Confused">Confused</a> for 5 seconds</li></ul>',
            speed: 'Average',
            duration: '',
            range: '10m + 8m Jump',
            area: 'Foe Target + 5 Jump Targets',
            description: 'Destroys an enemy\'s memory with calculated accuracy, leaving them Dazed and Confused before rapidly jumping to up to five other enemies.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/Stasis_Shell',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/74/Stasis_shell_icon.png',
            name: 'Stasis Shell',
            focus: '70&#160;',
            effects: '<ul><li>Foe Target: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Stasis_Shield?action=edit&amp;redlink=1" class="new" title="Stasis Shield (page does not exist)">Stasis Shield</a></li></ul>',
            speed: 'Average',
            duration: '20.0 seconds',
            range: '10m',
            area: 'Foe Target',
            description: 'The cipher is able to isolate a single enemy from the world, leaving them unable to act, but also unable to be affected by outside parties.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/Time_Parasite',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/5f/Time_parasite_icon.png',
            name: 'Time Parasite',
            focus: '70&#160;',
            effects: '<ul><li>Foe Target: Steal 50% of <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Attack_Speed" title="Attack Speed">Attack Speed</a></li><li>Foe Jump Targets (x5): Steal 50% of <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Attack_Speed" title="Attack Speed">Attack Speed</a></li></ul>',
            speed: 'Average',
            duration: '12.0 seconds',
            range: '10m + 10m Jump',
            area: 'Foe Target + 5 Foe Jump Targets',
            description: 'By siphoning power from enemies\' souls, the cipher is able to slow them down and increase his or her own speed.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Defensive_Mindweb',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/61/Defensive_mindweb_icon.png',
            name: 'Defensive Mindweb',
            focus: '80&#160;',
            effects: '<ul><li>Friendly Aura: All allies in the mindweb use the best defense of anyone in the web</li></ul>',
            speed: 'Instant',
            duration: '30.0 seconds',
            range: '',
            area: 'Aura Range: 3m',
            description: 'By linking his or her mind with those of nearby allies, the caster creates a series of defensive links between them. All allies in the mindweb use the best defense of anyone in the web.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Reaping_Knives',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/43/Reaping_knives_icon.png',
            name: 'Reaping Knives',
            focus: '80&#160;',
            effects: '<ul><li>Allied Target: Summon Weapon: <a target="_blank" href="https://pillarsofeternity.fandom.com/wiki/Reaping_Knives_(item)" title="Reaping Knives (item)">Reaping Knives</a> (x2)</li></ul>',
            speed: 'Average',
            duration: '30.0 seconds',
            range: '2m',
            area: 'Allied Target',
            description: 'The cipher uses an ally\'s soul to create "blades" of pure energy that emerge from both hands. The blades do Raw damage and generate Focus for the cipher who created them.',
        },
    ],
    talents: [
        {
            name: 'Biting Whip',
            effects: 'As long as the cipher\'s <a href="/wiki/Focus" class="mw-redirect" title="Focus">Focus</a> is below maximum, their <a href="/wiki/Soul_Whip" title="Soul Whip">Soul Whip</a> deals 20% more damage in melee and ranged <a href="/wiki/Combat" title="Combat">combat</a>.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Biting_Whip',
            imageLink: cipherPassiveImageLink
        },
        {
            name: 'Psychic Backlash',
            effects: 'Whenever the cipher is attacked, targeting their Will <a href="/wiki/Defense" title="Defense">defense</a>, the attacker may get <a href="/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a> themselves, with the cipher\'s <a href="/wiki/Accuracy" title="Accuracy">Accuracy</a> -10 counting against their own Will.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Psychic_Backlash',
            imageLink: cipherPassiveImageLink
        },
        {
            name: 'Brutal Backlash',
            effects: 'Whenever the cipher\'s <a href="/wiki/Psychic_Backlash" title="Psychic Backlash">Psychic Backlash</a> talent strikes, this brutal upgrade adds 20 <a href="/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage to the <a href="/wiki/Stunned" class="mw-redirect" title="Stunned">stunned effect</a>.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Brutal_Backlash',
            imageLink: cipherPassiveImageLink,
            requiredTalent: 'Psychic Backlash'
        },
        {
            name: 'Draining Whip',
            effects: 'As long as the cipher\'s <a href="/wiki/Focus" class="mw-redirect" title="Focus">focus</a> hasn\'t reached its maximum, their <a href="/wiki/Soul_Whip" title="Soul Whip">Soul Whip</a> will generate 33% more <a href="/wiki/Focus" class="mw-redirect" title="Focus">Focus</a> while in <a href="/wiki/Combat" title="Combat">combat</a>.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Draining_Whip',
            imageLink: cipherPassiveImageLink
        },
        {
            name: 'Greater Focus',
            effects: 'The cipher\'s maximum <a href="/wiki/Focus" class="mw-redirect" title="Focus">Focus</a> is increased by 10.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Greater_Focus',
            imageLink: cipherPassiveImageLink
        }
    ]
};
