const druidPassiveImageLink = 'https://static.wikia.nocookie.net/eternitywiki/images/5/52/Druid_passive_icon.png';
const commonPassiveImageLink = 'https://static.wikia.nocookie.net/eternitywiki/images/0/0f/Generic_passive_icon.png';

export default {
    name: 'Druid',
    endurancePerLevel: 12,
    healthMultiplier: 4,
    accuracy: 20,
    deflection: 20,
    skillBonuses: {
        Lore: +1,
        Survival: +2
    },
    baseAbility: null,
    abilities: [
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Charm_Beast',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/b/ba/Charm_beast_icon.png',
            name: 'Charm Beast',
            effects: '<ul><li>Foe AoE (Only <a href="https://pillarsofeternity.fandom.com/wiki/Beasts" class="mw-redirect" title="Beasts">Beasts</a>): <a href="https://pillarsofeternity.fandom.com/wiki/Charmed" class="mw-redirect" title="Charmed">Charmed</a></li></ul>',
            speed: 'Average',
            duration: '8.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '5m',
            area: '1.25m Radius',
            description: 'The druid utilizes his or her innate connection with the natural world to Charm enemy animals in the area of effect.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Dancing_Bolts',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d8/Dancing_bolts_icon.png',
            name: 'Dancing Bolts',
            effects: '<ul><li>Foe AoE: 15-25 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '0.5 sec (Average)',
            range: '15m',
            area: '3.0m Radius',
            description: 'Summons a flurry of thin bolts of lightning, hitting enemies in the area of effect with Shock damage.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Nature%27s_Mark',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/b/b2/Natures_mark_icon.png',
            name: 'Nature\'s Mark',
            effects: '<ul><li>Foe AoE: -10 <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a></li><li>Foe AoE: -10 <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" class="mw-redirect" title="Reflex">Reflex</a></li></ul>',
            speed: 'Fast',
            duration: '30.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '10m',
            area: '2.5m Radius',
            description: 'Causes enemies in the area of effect to glow with pale green light, making them easier targets. Affected enemies suffer decreased Deflection and Reflex.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Nature%27s_Vigor',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/7d/Natures_vigor_icon.png',
            name: 'Nature\'s Vigor',
            effects: '<ul><li>Friendly AoE: +40 <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a></li><li>Friendly AoE: +15% Maximum <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a></li></ul>',
            speed: 'Fast',
            duration: '12.0 seconds',
            interrupt: '',
            range: '',
            area: '1.25m Radius from Caster',
            description: 'Draws on the invigorating power of nature, creating a mild regeneration effect and raising Max Endurance on party members.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Sunbeam',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/15/Sunbeam_icon.png',
            name: 'Sunbeam',
            effects: '<ul><li>AoE: 20-35 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Blinded" class="mw-redirect" title="Blinded">Blinded</a></li></ul>',
            speed: 'Average',
            duration: '15.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '15m',
            area: '1.25m Radius',
            description: 'Calls down a shaft of intense sunlight, burning and potentially Blinding those caught in the area of effect.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Talons%27_Reach',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/b/b3/Talons_reach_icon.png',
            name: 'Talons\' Reach',
            effects: '<ul><li>Foe AoE: 25-40 <a href="https://pillarsofeternity.fandom.com/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            speed: 'Fast',
            duration: '',
            interrupt: '0.75 sec (Strong)',
            range: '6m',
            area: '1.25m Radius',
            description: 'Conjures a giant pair of razor-sharp talons, causing Slash damage to all in the area of effect.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Tanglefoot',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/5a/Tanglefoot_icon.png',
            name: 'Tanglefoot',
            effects: '<ul><li>AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a> for 4 seconds</li></ul>',
            speed: 'Fast',
            duration: '20.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '10m',
            area: 'Ground: 5.0m Radius',
            description: 'Rapidly grows a patch of twisted vines that surround and entangle anyone unlucky enough to get caught inside. Characters who set foot inside the area of effect become Hobbled.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Vile_Thorns',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/da/Vile_thorns_icon.png',
            name: 'Vile Thorns',
            effects: '<ul><li>AoE: 26-38 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>AoE: If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a> (<a href="https://pillarsofeternity.fandom.com/wiki/Poison" class="mw-redirect" title="Poison">Poison</a>) for 10 seconds (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '10.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 3.0m 90В° Cone',
            description: 'Shoots sharp-thorned vines up through the ground, causing Pierce damage and potentially Sickening anyone in the area of effect.',
        },
        {
            level: '1',
            link: 'https://pillarsofeternity.fandom.com/wiki/Winter_Wind',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/ff/Winter_wind_icon.png',
            name: 'Winter Wind',
            effects: '<ul><li>Foe AoE: 22-32 <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>Foe AoE: 2.0m Push</li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '1.0 sec (Stronger)',
            range: '',
            area: 'Length: 8.0m 60В° Cone',
            description: 'Causes an icy wind of incredible power to arise, pushing back all in the area of effect and inflicting Freeze damage.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Autumn%27s_Decay',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/fe/Autumns_decay_icon.png',
            name: 'Autumn\'s Decay',
            effects: '<ul><li>AoE: 15-25 <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>AoE: 45 <a href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png" decoding="async" width="18" height="18" /></a> damage over time</li></ul>',
            speed: 'Average',
            duration: '6.0 seconds',
            interrupt: '0.35 sec (Weak)',
            range: '',
            area: 'Length: 5.0m 90В° Cone',
            description: 'Creates a cone of putrefaction, causing immediate Corrosive damage and then more damage over time to any in the area of effect.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Blizzard',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/65/Blizzard_icon.png',
            name: 'Blizzard',
            effects: '<ul><li>AoE: 18-25 <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>AoE: -20% &#160;<a href="https://pillarsofeternity.fandom.com/wiki/Attack_Speed" title="Attack Speed">Attack Speed</a></li></ul>',
            speed: 'Average',
            duration: '10.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '15m',
            area: '2.5m Radius',
            description: 'Conjures a violent storm of ice and snow, slowing inflicting Freeze damage upon any in the area of effect and slowing their Attack Rate.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Burst_of_Summer_Flame',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/20/Summer_flame_icon.png',
            name: 'Burst of Summer Flame',
            effects: '<ul><li>AoE: 35-45 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '0.2 sec (Weaker)',
            range: '15m',
            area: '1.25m Radius',
            description: 'Quickly generates an explosive flash of flame, inflicting Burn damage to anyone in the area of effect. Short cast time.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Conjure_Lesser_Blight',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/f1/Conjure_lesser_blight_icon.png',
            name: 'Conjure Lesser Blight',
            effects: '<ul><li>Summon 1 of: <a href="https://pillarsofeternity.fandom.com/wiki/Small_Rain_Blight" title="Small Rain Blight">Small Rain Blight</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Small_Wind_Blight" title="Small Wind Blight">Small Wind Blight</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Small_Earth_Blight" title="Small Earth Blight">Small Earth Blight</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Small_Flame_Blight" title="Small Flame Blight">Small Flame Blight</a></li></ul>',
            speed: 'Slow',
            duration: '20.0 seconds',
            interrupt: '',
            range: '6m',
            area: '',
            description: 'Gathers a few stray soul fragments, coalescing them into a Lesser Flame, Wind, Rain, or Earth Blight.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Firebrand_(ability)',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e4/Firebrand_icon.png',
            name: 'Firebrand (ability)',
            effects: '<ul><li>Summon Weapon: <a href="https://pillarsofeternity.fandom.com/wiki/Firebrand_(item)" title="Firebrand (item)">Firebrand</a></li></ul>',
            speed: 'Fast',
            duration: '30.0 seconds',
            interrupt: '',
            range: '',
            area: 'Caster',
            description: 'Forms a powerful sword with a blade of pure fire in the caster\'s hands that inflicts Burn damage. Switching to another weapon ends the spell.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Hold_Beasts',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/a1/Hold_beasts_icon.png',
            name: 'Hold Beasts',
            effects: '<ul><li>Foe AoE (Only <a href="https://pillarsofeternity.fandom.com/wiki/Beasts" class="mw-redirect" title="Beasts">Beasts</a>): <a href="https://pillarsofeternity.fandom.com/wiki/Paralyzed" class="mw-redirect" title="Paralyzed">Paralyzed</a></li></ul>',
            speed: 'Fast',
            duration: '7.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '15m',
            area: '1.25m Radius',
            description: 'Forces a shrieking cry from the caster\'s throat, Paralyzing all but the most fearsome of animals.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Insect_Swarm',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/63/Insect_swarm_icon.png',
            name: 'Insect Swarm',
            effects: '<ul><li>Foe AoE: 43.3 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage over time</li><li>Foe AoE: -10 <a href="https://pillarsofeternity.fandom.com/wiki/Concentration" class="mw-redirect" title="Concentration">Concentration</a></li></ul>',
            speed: 'Average',
            duration: '10.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '15m',
            area: '1.25m Radius',
            description: 'Attracts a swarm of aggressive insects, causing Pierce Damage over time and reducing the concentration of anyone in the area of effect.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Taste_of_the_Hunt',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/5b/Taste_of_the_hunt_icon.png',
            name: 'Taste of the Hunt',
            effects: '<ul><li>Target: 30 <a href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage over time</li><li>Caster: 100% of <a href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">Damage</a> restored as <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a></li></ul>',
            speed: 'Average',
            duration: '10.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: '',
            description: 'Caster\'s melee weapon becomes an ideal instrument for hunting, adding continuous Raw Damage to its attack and restoring Endurance to the caster with every hit.',
        },
        {
            level: '3',
            link: 'https://pillarsofeternity.fandom.com/wiki/Woodskin',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/f4/Woodskin_icon.png',
            name: 'Woodskin',
            effects: '<ul><li>Friendly AoE: +6 <a href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
            speed: 'Fast',
            duration: '15.0 seconds',
            interrupt: '',
            range: '5m',
            area: '1.25m Radius',
            description: 'Creates a thick layer of bark over allies in the area of effect, affording them a Damage Reduction bonus to Pierce, Slash, Burn, and Shock.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Beetle_Shell_(ability)',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d5/Beetles_shell_icon.png',
            name: 'Beetle Shell (ability)',
            effects: '<ul><li>Friendly Target: 100-pt <a href="https://pillarsofeternity.fandom.com/wiki/Stasis_Shield?action=edit&amp;redlink=1" class="new" title="Stasis Shield (page does not exist)">Stasis Shield</a></li></ul>',
            speed: 'Fast',
            duration: '30.0 seconds',
            interrupt: '',
            range: '15m',
            area: '',
            description: 'Encases the target in a protective shell, absorbing a fixed amount of damage before shattering, but preventing the target from taking actions (including moving).',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Infestation_of_Maggots',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/82/Infestation_of_maggots_icon.png',
            name: 'Infestation of Maggots',
            effects: '<ul><li>Foe AoE: 10 <a href="https://pillarsofeternity.fandom.com/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png" decoding="async" width="18" height="18" /></a> by percentage of <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png" decoding="async" width="16" height="16" /></a> lost</li></ul>',
            speed: 'Average',
            duration: '20.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '10m',
            area: '1.25m Radius',
            description: 'Enemies in the area of effect have their skin infested by hordes of burrowing maggots, inflicting Raw damage over time. The more wounded the target, the greater the damage. A target at maximum Endurance takes no damage from the spell.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Nature%27s_Balm',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/ed/Natures_balm_icon.png',
            name: 'Nature\'s Balm',
            effects: '<ul><li>Friendly AoE: +60 <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> over time</li></ul>',
            speed: 'Fast',
            duration: '15.0 seconds',
            interrupt: '',
            range: '',
            area: '1.25m Radius from Caster',
            description: 'Draws on the healing power of nature, creating a rapid regeneration effect on party members.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Purge_of_Toxins',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/b/b5/Purge_of_toxins_icon.png',
            name: 'Purge of Toxins',
            effects: '<ul><li>Friendly Target: Immunity: <a href="https://pillarsofeternity.fandom.com/wiki/Poison" class="mw-redirect" title="Poison">Poison</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Disease?action=edit&amp;redlink=1" class="new" title="Disease (page does not exist)">Disease</a></li></ul>',
            speed: 'Fast',
            duration: '30.0 seconds',
            interrupt: '',
            range: '6m',
            area: '',
            description: 'Purifies the target of any toxic presence in its body, giving immunity to Poison and Disease effects.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Returning_Storm',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/ae/Returning_storm_icon.png',
            name: 'Returning Storm',
            effects: '<ul><li>Foe AoE: 20-30 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a> damage (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe AoE: If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a> for 3 seconds (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Slow',
            duration: '30.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: '5.0m Radius from Caster',
            description: 'Brings a powerful storm into being, striking a random single enemy in the area of effect periodically with bolts of lightning that Stun and deal Shock damage.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Spreading_Plague',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/ef/Spreading_plague_icon.png',
            name: 'Spreading Plague',
            effects: '<ul><li>Foe Target: <a href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a></li><li>Foe Jump Targets (x5): <a href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a></li></ul>',
            speed: 'Average',
            duration: '15.0 seconds',
            interrupt: '',
            range: '10m + 5m Jump',
            area: 'Foe Target + 5 Jump Targets',
            description: 'Infects the target with a virulent and debilitating disease, Hobbling and Weakening them before spreading to other enemies.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Stag%27s_Horn',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d0/Stags_horn_icon.png',
            name: 'Stag\'s Horn',
            effects: '<ul><li>Target: 30-55 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>Target: -10 <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a></li><li>Target: -10 <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" class="mw-redirect" title="Reflex">Reflex</a></li></ul>',
            speed: 'Average',
            duration: '10.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '10m',
            area: '',
            description: 'Conjures an enormous stag horn to attack the target, causing Piercing damage and inflicting a penalty to Deflection and Reflex.',
        },
        {
            level: '5',
            link: 'https://pillarsofeternity.fandom.com/wiki/Twin_Stones',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/7a/Twin_stones_icon.png',
            name: 'Twin Stones',
            effects: '<ul><li>Foe Target: 20 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe AoE: 25-40 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 6.0m + 2.5m Radius',
            description: 'Sends two deadly boulders flying out from the druid\'s position, dealing Crush damage to anyone in their path and exploding on contact with a solid surface, causing the fragments to Pierce anyone nearby.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Boiling_Spray',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/0e/Boiling_spray_icon.png',
            name: 'Boiling Spray',
            effects: '<ul><li>AoE: 40-50 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>AoE: 2.0m Push</li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 6.0m 90В° Cone',
            description: 'Everyone in the cone area of effect takes Burn damage and is pushed back.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Calling_the_World%27s_Maw',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/a8/Calling_the_worlds_maw_icon.png',
            name: 'Calling the World\'s Maw',
            effects: '<ul><li>AoE: 25-48 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>AoE: If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Prone" class="mw-redirect" title="Prone">Prone</a> (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '7.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '10m',
            area: '2.5m Radius',
            description: 'Summons a jagged rock to stab upward from the ground, dealing Pierce damage to targets and knocking them Prone.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Conjure_Blight',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/52/Conjure_blight_icon.png',
            name: 'Conjure Blight',
            effects: '<ul><li>Summon 1 of: <a href="https://pillarsofeternity.fandom.com/wiki/Rain_Blight" title="Rain Blight">Rain Blight</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Wind_Blight" title="Wind Blight">Wind Blight</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Earth_Blight" title="Earth Blight">Earth Blight</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Flame_Blight" title="Flame Blight">Flame Blight</a></li></ul>',
            speed: 'Slow',
            duration: '25.0 seconds',
            interrupt: '',
            range: '',
            area: '',
            description: 'Gathers a moderate amount of stray soul fragments, coalescing them into a Flame, Wind, Rain, or Earth Blight.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Form_of_the_Delemgan',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/fc/Form_of_the_delemgan_icon.png',
            name: 'Form of the Delemgan',
            effects: '<ul><li>Friendly AoE: +8 <a href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a></li><li>Friendly AoE: +1 <a href="https://pillarsofeternity.fandom.com/wiki/Move_Speed" title="Move Speed">Move Speed</a></li><li>Friendly AoE: +25 <a href="https://pillarsofeternity.fandom.com/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a> on <a href="https://pillarsofeternity.fandom.com/wiki/Disengagement" class="mw-redirect" title="Disengagement">Disengagement</a></li><li>Friendly AoE: Immunity: <a href="https://pillarsofeternity.fandom.com/wiki/Stuck" class="mw-redirect" title="Stuck">Stuck</a></li></ul>',
            speed: 'Fast',
            duration: '20.0 seconds',
            interrupt: '',
            range: '5m',
            area: '3.0m Radius',
            description: 'Allies gain a protective layer of wooden "skin" and are imbued with characteristics of delemgan, becoming faster, less vulnerable to Disengagement attacks, and immune to the Stuck affliction.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Hail_Storm',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e5/Hail_storm_icon.png',
            name: 'Hail Storm',
            effects: '<ul><li>AoE: 30-42 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>AoE: 25% <a href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">damage</a> as <a href="https://pillarsofeternity.fandom.com/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '0.5 sec (Average)',
            range: '15m',
            area: '5.0m Radius',
            description: 'Calls down a savage storm of sleet and ice chunks, causing Crush and Freeze damage to any in the area of effect.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Moonwell',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/f3/Moonwell_icon.png',
            name: 'Moonwell',
            effects: '<ul><li>Friendly AoE: +92 <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> over time</li><li>Friendly AoE: +10 All <a href="https://pillarsofeternity.fandom.com/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a></li></ul>',
            speed: 'Average',
            duration: '20.0 seconds',
            interrupt: '',
            range: '6m',
            area: '2.5m Radius',
            description: 'Channels lunar energy into a localized source of power, regenerating the Endurance of allies in the area of effect and granting a minor bonus to all Defenses.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Overwhelming_Wave',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/68/Overwhelming_wave_icon.png',
            name: 'Overwhelming Wave',
            effects: '<ul><li>Target: 30-40 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>Target: <a href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a></li></ul>',
            speed: 'Average',
            duration: '8.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 10m',
            description: 'Conjures a rolling wave of water that plows through everything in its path, causing Crush damage and the Stun affliction.',
        },
        {
            level: '7',
            link: 'https://pillarsofeternity.fandom.com/wiki/Wicked_Briars',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8e/Wicked_briars_icon.png',
            name: 'Wicked Briars',
            effects: '<ul><li>AoE: 10-15 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>AoE: If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Hobbled" class="mw-redirect" title="Hobbled">Hobbled</a> for 3 seconds (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Fast',
            duration: '20.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '6m',
            area: 'Ground: 2.5m Radius',
            description: 'Sprouts thick, thorny vines from the ground, causing Pierce damage to and Hobbling any in the area of effect.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Cleansing_Wind',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/92/Cleansing_wind_icon.png',
            name: 'Cleansing Wind',
            effects: '<ul><li>Foe Target: 3.0m Push (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Friendly Target: +32 <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a></li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 10m',
            description: 'Creates a rolling cloud of purification, healing the Endurance of allies and pushing back enemies.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Embrace_the_Earth-Talon',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/36/Embrace_the_earth_talon_icon.png',
            name: 'Embrace the Earth-Talon',
            effects: '<ul><li>AoE: 28-38 <a href="https://pillarsofeternity.fandom.com/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a> damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>AoE: If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Petrified" class="mw-redirect" title="Petrified">Petrified</a> (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '6.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: '1.25m Radius',
            description: 'A trio of stone claws erupt from the ground, petrifying and inflicting Slash damage on everyone caught in the area.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Firebug',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/2/2a/Firebug_icon.png',
            name: 'Firebug',
            effects: '<ul><li>Foe Target: 30-40 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe Jump Targets (x8): 30-40 <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '0.5 sec (Average)',
            range: '10m + 5m Jump',
            area: 'Foe Target + 8 Jump Targets',
            description: 'A fearsome ball of fire bounces from enemy to enemy up to eight times, causing Burn damage.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Nature%27s_Terror',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e7/Natures_terror_icon.png',
            name: 'Nature\'s Terror',
            effects: '<ul><li>AoE: 10-15 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a> damage (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>AoE: If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a> for 3 seconds (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Fast',
            duration: '30.0 seconds',
            interrupt: '',
            range: '',
            area: '1.25m Radius from Caster',
            description: 'Calls upon the dreadful strength of the storm, granting an electrical aura that deals Shock damage to and Terrifies anyone nearby.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Plague_of_Insects',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/dd/Plague_of_insects_icon.png',
            name: 'Plague of Insects',
            effects: '<ul><li>Foe AoE: 88 <a href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage over time</li><li>Foe AoE: -20 <a href="https://pillarsofeternity.fandom.com/wiki/Concentration" class="mw-redirect" title="Concentration">Concentration</a></li><li>Foe AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Sickened" class="mw-redirect" title="Sickened">Sickened</a></li></ul>',
            speed: 'Average',
            duration: '30.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '15m',
            area: '5.0m Radius',
            description: 'Summons an enormous infestation of venomous insects, dealing Raw damage over time, reducing Concentration and Sickening anyone in the area of effect.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Relentless_Storm',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/f7/Relentless_storm_icon.png',
            name: 'Relentless Storm',
            effects: '<ul><li>Foe AoE: 9-12 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a> damage (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe AoE: If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a> for 2 seconds (+10 <a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '15.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: '5.0m Radius from Caster',
            description: 'Brings a deadly storm into being, striking enemies frequently in the area of effect with lightning bolts that Stun and deal Shock damage.',
        },
        {
            level: '9',
            link: 'https://pillarsofeternity.fandom.com/wiki/Wall_of_Thorns',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/c/cd/Wall_of_thorns_icon.png',
            name: 'Wall of Thorns',
            effects: '<ul><li>Hazard AoE: 4-6 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>Hazard AoE: <a href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a> for 5 seconds</li></ul>',
            speed: 'Average',
            duration: '30.0 seconds',
            interrupt: '0.5 sec (Average)',
            range: '12m',
            area: '20m Wall',
            description: 'Creates a thick wall of gnarled thorns, inflicting Pierce damage. It also applies a Poison effect that inflicts a Weakened state, failing a Fortitude check.',
        },
        {
            level: '11',
            link: 'https://pillarsofeternity.fandom.com/wiki/Conjure_Greater_Blight',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/3/36/Conjure_greater_blight_icon.png',
            name: 'Conjure Greater Blight',
            effects: '<ul><li>Summon 1 of: <a href="https://pillarsofeternity.fandom.com/wiki/Greater_Rain_Blight" title="Greater Rain Blight">Greater Rain Blight</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Greater_Wind_Blight" title="Greater Wind Blight">Greater Wind Blight</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Greater_Earth_Blight" title="Greater Earth Blight">Greater Earth Blight</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Greater_Flame_Blight" title="Greater Flame Blight">Greater Flame Blight</a></li></ul>',
            speed: 'Slow',
            duration: '30.0 seconds',
            interrupt: '',
            range: '6m',
            area: '',
            description: 'Gathers an immense quantity of stray soul fragments and coalesces them into a Greater Flame, Wind, Rain, or Earth Blight.',
        },
        {
            level: '11',
            link: 'https://pillarsofeternity.fandom.com/wiki/Garden_of_Life',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Garden_of_life_icon.png',
            name: 'Garden of Life',
            effects: '<ul><li>Friendly AoE: +20 <a href="https://pillarsofeternity.fandom.com/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a></li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '',
            range: '15m',
            area: 'Target + 5.0m Radius',
            description: 'Hastens Berath\'s Wheel, causing rejuvenating plants to spring up in the corpses of the fallen and heal allies in the area of effect.',
        },
        {
            level: '11',
            link: 'https://pillarsofeternity.fandom.com/wiki/Rot_Skulls',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/16/Rot_skulls_icon.png',
            name: 'Rot Skulls',
            effects: '<ul><li>Summon Weapon: <a href="https://pillarsofeternity.fandom.com/wiki/Rot_Skull" title="Rot Skull">Rot Skull</a></li></ul>',
            speed: 'Fast',
            duration: '30.0 seconds',
            interrupt: '',
            range: '',
            area: 'Caster',
            description: 'Creates rotting, disease-riddled skulls in hand of the caster, acting as a ranged weapon that cause Crush damage and apply a Disease-based Corrode area of effect that does damage over time.',
        },
        {
            level: '11',
            link: 'https://pillarsofeternity.fandom.com/wiki/Sunlance',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d1/Sunlance_icon.png',
            name: 'Sunlance',
            effects: '<ul><li>Target: 46-58 <a href="https://pillarsofeternity.fandom.com/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>Target: +50% <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a> damage</li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '0.5 sec (Average)',
            range: '20m',
            area: '',
            description: 'Calls down a powerful lance of sunlight from the sky, inflicting Pierce and Burn damage upon a single target.',
        },
        {
            level: '11',
            link: 'https://pillarsofeternity.fandom.com/wiki/Venombloom',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/75/Venombloom_icon.png',
            name: 'Venombloom',
            effects: '<ul><li>Foe AoE: 10-15 <a href="https://pillarsofeternity.fandom.com/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage</li><li>Foe AoE: If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Weakened" class="mw-redirect" title="Weakened">Weakened</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a> for 3 seconds</li></ul>',
            speed: 'Average',
            duration: '15.0 seconds',
            interrupt: '',
            range: '10m',
            area: 'Poison: 2.5m Radius',
            description: 'Grows a beautiful but panic-inducing field of poisonous flowers that Frighten, Weaken and deal Raw Damage over time to those in the area of effect.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/Call_to_the_Primordials',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/73/Call_to_the_primordials_icon.png',
            name: 'Call to the Primordials',
            effects: '<ul><li>Summon 2-3 of: <a href="https://pillarsofeternity.fandom.com/wiki/Black_Ooze" title="Black Ooze">Black Ooze</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Frost_Ooze" title="Frost Ooze">Frost Ooze</a>, <a href="https://pillarsofeternity.fandom.com/wiki/Swamp_Slime" title="Swamp Slime">Swamp Slime</a></li></ul>',
            speed: 'Slow',
            duration: '35.0 seconds',
            interrupt: '',
            range: '6m',
            area: '',
            description: 'The druid pulls the raw spiritual energy of nature together into the physical forms of 2 or 3 random oozes and slimes.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/Nature%27s_Bounty_(spell)',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/58/Natures_bounty_icon.png',
            name: 'Nature\'s Bounty (spell)',
            effects: '<ul><li>Allied AoE: Fill <a href="https://pillarsofeternity.fandom.com/wiki/Quick_Item?action=edit&amp;redlink=1" class="new" title="Quick Item (page does not exist)">Quick Items</a> with <a href="https://pillarsofeternity.fandom.com/wiki/Potion_of_Nature%27s_Bounty" title="Potion of Nature&#39;s Bounty">Nature\'s Bounty</a></li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '',
            range: '',
            area: '5.0m Radius from Caster',
            description: 'All unoccupied quick slots in the party are filled with wondrous nectar that can be consumed for combat bonuses and healing.',
        },
        {
            level: '13',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weather_the_Storm',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e7/Weather_the_storm_icon.png',
            name: 'Weather the Storm',
            effects: '<ul><li>Friendly AoE: +15 <a href="https://pillarsofeternity.fandom.com/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png" decoding="async" width="18" height="18" /></a><a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a></li></ul>',
            speed: 'Average',
            duration: '10.0 seconds',
            interrupt: '',
            range: '5m',
            area: '2.5m Radius',
            description: 'The druid casts a powerful aegis against the forces of nature over his or her allies, granting large resistance to Burn, Corrode, Freeze, and Shock damage.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Avenging_Storm',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/7d/Avenging_storm_icon.png',
            name: 'Avenging Storm',
            effects: '<ul><li>Foe hitting Caster: 20-30 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a> damage (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe hitting Caster: If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a> for 0.8 second (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe hit by Caster: 20-30 <a href="https://pillarsofeternity.fandom.com/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png" decoding="async" width="18" height="18" /></a> damage (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>Foe hit by Caster: If successful: <a href="https://pillarsofeternity.fandom.com/wiki/Stunned" class="mw-redirect" title="Stunned">Stunned</a> for 0.8 second (<a href="https://pillarsofeternity.fandom.com/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="https://pillarsofeternity.fandom.com/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Fast',
            duration: '20.0 seconds',
            interrupt: '',
            range: '',
            area: '',
            description: 'The druid makes himself or herself a conduit for the power of a storm. Any target they strike in melee, or who strikes them in melee, is attacked by a bolt of lightning.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Fire_Stag',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/44/Fire_stag_icon.png',
            name: 'Fire Stag',
            effects: '<ul><li>Summon: <a href="https://pillarsofeternity.fandom.com/wiki/Stag" title="Stag">Stag</a></li></ul>',
            speed: 'Slow',
            duration: '35.0 seconds',
            interrupt: '',
            range: '6m',
            area: '',
            description: 'The druid coalesces tiny nature spirits into the form of a great stag made of flame. The stag leaves a trail of fire wherever it runs. The spirits inside can be made to disperse violently, destroying the stag but doing Fire or Pierce damage to anyone caught in the blast.',
        },
        {
            level: '15',
            link: 'https://pillarsofeternity.fandom.com/wiki/Tornado',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/e/e1/Tornado_icon.png',
            name: 'Tornado',
            effects: '<ul><li>Target: 45-55 <a href="https://pillarsofeternity.fandom.com/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> damage, <a href="https://pillarsofeternity.fandom.com/wiki/Prone" class="mw-redirect" title="Prone">Prone</a></li><li>On bounce: -50% <a href="https://pillarsofeternity.fandom.com/wiki/Damage" class="mw-redirect" title="Damage">damage</a></li></ul>',
            speed: 'Average',
            duration: '',
            interrupt: '0.5 sec (Average)',
            range: '',
            area: 'Length: 30m, bounces up to 3 times',
            description: 'Conjures a destructive vortex of wind that can launch people into the air, knock victims Prone, and inflict Crush damage on everyone it touches.',
        },
    ],
    spiritForms: [
        {
            name: 'Bear',
            link: 'https://pillarsofeternity.fandom.com/wiki/Spiritshift_Bear',
            damageType: 'Slash'
        },
        {
            name: 'Boar'
        },
        {
            name: 'Cat'
        },
        {
            name: 'Stag'
        },
        {
            name: 'Wolf'
        },
        {
            name: 'Stelgaer',
            companionOnly: true
        }
    ],
    talents: [
        {
            name: 'Wildstrike Shock',
            effects: '<ul><li>+30% <a href="/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235346" decoding="async" width="18" height="18"></a> damage</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Wildstrike_Shock',
            imageLink: druidPassiveImageLink,
            exceptionalTalents: ['Wildstrike Burn', 'Wildstrike Freeze', 'Wildstrike Corrode']
        },
        {
            name: 'Wildstrike Burn',
            effects: '<ul><li>+30% <a href="/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235248" decoding="async" width="18" height="18"></a> damage</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Wildstrike_Burn',
            imageLink: druidPassiveImageLink,
            exceptionalTalents: ['Wildstrike Shock', 'Wildstrike Freeze', 'Wildstrike Corrode']
        },
        {
            name: 'Wildstrike Freeze',
            effects: '<ul><li>+30% <a href="/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png/revision/latest/scale-to-width-down/18?cb=20170909202622" decoding="async" width="18" height="18"></a> damage</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Wildstrike_Freeze',
            imageLink: druidPassiveImageLink,
            exceptionalTalents: ['Wildstrike Shock', 'Wildstrike Burn', 'Wildstrike Corrode']
        },
        {
            name: 'Wildstrike Corrode',
            effects: '<ul><li>+30% <a href="/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235258" decoding="async" width="18" height="18"></a> damage</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Wildstrike_Corrode',
            imageLink: druidPassiveImageLink,
            exceptionalTalents: ['Wildstrike Shock', 'Wildstrike Burn', 'Wildstrike Freeze']
        },
        {
            name: 'Greater Wildstrike Shock',
            effects: '<ul><li>+15% <a href="/wiki/Shock" title="Shock"><img alt="Shock" src="https://static.wikia.nocookie.net/eternitywiki/images/8/89/Shock_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235346" decoding="async" width="18" height="18"></a> damage</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Greater_Wildstrike_Shock',
            imageLink: druidPassiveImageLink,
            requiredTalent: 'Wildstrike Shock'
        },
        {
            name: 'Greater Wildstrike Burn',
            effects: '<ul><li>+15% <a href="/wiki/Burn" title="Burn"><img alt="Burn" src="https://static.wikia.nocookie.net/eternitywiki/images/a/aa/Burn_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235248" decoding="async" width="18" height="18"></a> damage</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Greater_Wildstrike_Burn',
            imageLink: druidPassiveImageLink,
            requiredTalent: 'Wildstrike Burn'
        },
        {
            name: 'Greater Wildstrike Freeze',
            effects: '<ul><li>+15% <a href="/wiki/Freeze" title="Freeze"><img alt="Freeze" src="https://static.wikia.nocookie.net/eternitywiki/images/9/95/Freeze_icon.png/revision/latest/scale-to-width-down/18?cb=20170909202622" decoding="async" width="18" height="18"></a> damage</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Greater_Wildstrike_Freeze',
            imageLink: druidPassiveImageLink,
            requiredTalent: 'Wildstrike Freeze'
        },
        {
            name: 'Greater Wildstrike Corrode',
            effects: '<ul><li>+15% <a href="/wiki/Corrode" title="Corrode"><img alt="Corrode" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Corrode_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235258" decoding="async" width="18" height="18"></a> damage</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Greater_Wildstrike_Corrode',
            imageLink: druidPassiveImageLink,
            requiredTalent: 'Wildstrike Corrode'
        },
        {
            name: 'Bonus 1st Level Spell',
            description: 'Gain an extra spell cast of level 1 spells.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Bonus_1st_Level_Spell',
            imageLink: commonPassiveImageLink
        },
        {
            name: 'Bonus 2nd Level Spell',
            description: 'Gain an extra spell cast of level 2 spells.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Bonus_2nd_Level_Spell',
            imageLink: commonPassiveImageLink
        },
        {
            name: 'Bonus 3rd Level Spell',
            description: 'Gain an extra spell cast of level 3 spells.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Bonus_3rd_Level_Spell',
            imageLink: commonPassiveImageLink
        },
        {
            name: 'Bonus 4th Level Spell',
            description: 'Gain an extra spell cast of level 4 spells.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Bonus_4th_Level_Spell',
            imageLink: commonPassiveImageLink
        }
    ]
};
