const fighterPassiveImageLink = 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png';

export default {
    name: 'Fighter',
    endurancePerLevel: 14,
    healthMultiplier: 5,
    accuracy: 30,
    deflection: 30,
    skillBonuses: {
        Athletics: +1,
        Lore: +1,
        Survival: +1
    },
    baseAbility: {
        name: 'Constant Recovery',
        link: 'https://pillarsofeternity.fandom.com/wiki/Constant_Recovery',
        imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d5/Constant_recovery_icon.png',
        level: '1',
        activation: 'Passive',
        effects: '<ul><li>Self: +5 <a href="/wiki/Endurance" class="mw-redirect" title="Endurance">Endurance</a> per 3 seconds</li></ul>',
        speed: '',
        duration: '45.0 seconds',
        description: 'Charged by the rush of battle, the fighter will continually regenerate Endurance at a modest rate.',
    },
    abilities: [
        {
            name: 'Disciplined Barrage',
            link: 'https://pillarsofeternity.fandom.com/wiki/Disciplined_Barrage',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/f/f9/Disciplined_barrage_icon.png',
            level: '1',
            activation: 'Active',
            effects: '<ul><li>User: +20 <a href="/wiki/Accuracy" title="Accuracy">Accuracy</a></li></ul>',
            speed: 'Instant',
            duration: '15.0 seconds',
            description: 'The fighter intensely focuses on his or her training, significantly raising Accuracy for a short amount of time.',
        },
        {
            name: 'Knock Down',
            link: 'https://pillarsofeternity.fandom.com/wiki/Knock_Down',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/6/69/Knock_down_icon.png',
            level: '1',
            activation: 'Active',
            effects: '<ul><li>Target: <a href="/wiki/Prone" class="mw-redirect" title="Prone">Prone</a> (<a href="/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>User: <a href="/wiki/Full_Attack" class="mw-redirect" title="Full Attack">Full Attack</a>, +20% <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a> (<a href="/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '5.0 seconds',
            description: 'Shoves an enemy with enormous force, knocking them Prone and causing additional damage.',
        },
        {
            name: 'Confident Aim',
            link: 'https://pillarsofeternity.fandom.com/wiki/Confident_Aim',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '3',
            activation: 'Passive',
            effects: '<ul><li>Self: +20% <a href="/wiki/Graze" class="mw-redirect" title="Graze">Grazes</a> converted to <a href="/wiki/Hit" class="mw-redirect" title="Hit">Hits</a></li><li>Self: +20% Minimum <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a></li></ul>',
            speed: '',
            duration: '',
            description: 'Steadies the fighter\'s arm, causing a percentage of their Grazes to be converted to Hits and increasing the minimum damage for melee weapons.',
        },
        {
            name: 'Defender',
            link: 'https://pillarsofeternity.fandom.com/wiki/Defender',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/82/Defender_icon.png',
            level: '3',
            activation: 'Modal',
            effects: '<ul><li>User: +2 enemies <a href="/wiki/Engaged" class="mw-redirect" title="Engaged">Engaged</a></li><li>User: -5 <a href="/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a></li></ul>',
            speed: 'Instant',
            duration: '',
            description: 'The fighter adopts a more conservative combat strategy, concentrating on locking down enemies that stray too close. The fighter increases his or her number of Engagement targets to three, but at the expense of Deflection.',
        },
        {
            name: 'Guardian Stance',
            link: 'https://pillarsofeternity.fandom.com/wiki/Guardian_Stance',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/4/4a/Guardian_stance_icon.png',
            level: '3',
            activation: 'Modal',
            effects: '<ul><li>Friendly Aura: +10 <a href="/wiki/Deflection" class="mw-redirect" title="Deflection">Deflection</a></li><li>Self: -10 <a href="/wiki/Accuracy" title="Accuracy">Accuracy</a></li></ul>',
            speed: '',
            duration: '',
            description: 'The fighter devotes all his or her energy to defending allies. Lowers Accuracy but increases the Deflection of nearby allies.',
        },
        {
            name: 'Into The Fray',
            link: 'https://pillarsofeternity.fandom.com/wiki/Into_The_Fray',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/d/d5/Into_the_fray_icon.png',
            level: '5',
            activation: 'Active',
            effects: '<ul><li>Foe Target: 22-30 <a href="/wiki/Pierce" title="Pierce"><img alt="Pierce" src="https://static.wikia.nocookie.net/eternitywiki/images/5/52/Pierce_icon.png" decoding="async" width="18" height="18" /></a> damage, 5.0m Pull (<a href="/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a>)</li><li>If successful: <a href="/wiki/Dazed" class="mw-redirect" title="Dazed">Dazed</a> (<a href="/wiki/Accuracy" title="Accuracy"><img alt="Accuracy" src="https://static.wikia.nocookie.net/eternitywiki/images/d/df/Accuracy_icon.png" decoding="async" width="16" height="16" /></a> vs <a href="/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a>)</li></ul>',
            speed: 'Average',
            duration: '12.0 seconds',
            description: 'The fighter lunges through the battle, pulling an enemy into immediate melee range, causing Pierce damage, and leaving them Dazed.',
        },
        {
            name: 'Vigorous Defense',
            link: 'https://pillarsofeternity.fandom.com/wiki/Vigorous_Defense',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/9/99/Vigorous_defense_icon.png',
            level: '5',
            activation: 'Active',
            effects: '<ul><li>User: +20 All <a href="/wiki/Defense" title="Defenses"><img alt="Defenses" src="https://static.wikia.nocookie.net/eternitywiki/images/a/af/Defenses_icon.png" decoding="async" width="16" height="16" /></a></li></ul>',
            speed: 'Instant',
            duration: '15.0 seconds',
            description: 'The fighter becomes fiercely determined to deflect all incoming blows, dramatically increasing all Defenses for a short time.',
        },
        {
            name: 'Weapon Specialization: Adventurer',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Specialization:_Adventurer',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '5',
            activation: 'Passive',
            effects: '<ul><li>Self: +15% <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a> (<a href="/wiki/Pollaxe" title="Pollaxe">Pollaxe</a>, <a href="/wiki/Estoc" title="Estoc">Estoc</a>, <a href="/wiki/Flail" title="Flail">Flail</a>, <a href="/wiki/Wand" title="Wand">Wand</a>, <a href="/wiki/War_Bow" title="War Bow">War Bow</a>)</li></ul>',
            speed: '',
            duration: '',
            description: 'Weapon Specialization grants a damage bonus with all weapon types covered by the chosen specialization. Adventurer weapons include the Estoc, Flail, Pollaxe, Wand, and War Bow types.',
        },
        {
            name: 'Weapon Specialization: Knight',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Specialization:_Knight',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '5',
            activation: 'Passive',
            effects: '<ul><li>Self: +15% <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a> (<a href="/wiki/Battle_Axe" title="Battle Axe">Battle Axe</a>, <a href="/wiki/Sword" title="Sword">Sword</a>, <a href="/wiki/Morning_Star" title="Morning Star">Morning Star</a>, <a href="/wiki/Crossbow" title="Crossbow">Crossbow</a>)</li></ul>',
            speed: '',
            duration: '',
            description: 'Weapon Specialization grants a damage bonus with all weapon types covered by the chosen specialization. Knight weapons include the Battle Axe, Crossbow, Morning Star, and Sword types.',
        },
        {
            name: 'Weapon Specialization: Noble',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Specialization:_Noble',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '5',
            activation: 'Passive',
            effects: '<ul><li>Self: +15% <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a> (<a href="/wiki/Dagger" title="Dagger">Dagger</a>, <a href="/wiki/Rapier" title="Rapier">Rapier</a>, <a href="/wiki/Mace" title="Mace">Mace</a>, <a href="/wiki/Scepter" title="Scepter">Scepter</a>, <a href="/wiki/Rod" title="Rod">Rod</a>)</li></ul>',
            speed: '',
            duration: '',
            description: 'Weapon Specialization grants a damage bonus with all weapon types covered by the chosen specialization. Noble weapons include the Dagger, Mace, Rapier, Rod, and Scepter types.',
        },
        {
            name: 'Weapon Specialization: Peasant',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Specialization:_Peasant',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '5',
            activation: 'Passive',
            effects: '<ul><li>Self: +15% <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a> (<a href="/wiki/Hatchet" title="Hatchet">Hatchet</a>, <a href="/wiki/Spear" title="Spear">Spear</a>, <a href="/wiki/Quarterstaff" title="Quarterstaff">Quarterstaff</a>, <a href="/wiki/Hunting_Bow" title="Hunting Bow">Hunting Bow</a>, <a href="/wiki/Unarmed" class="mw-redirect" title="Unarmed">Unarmed</a>)</li></ul>',
            speed: '',
            duration: '',
            description: 'Weapon Specialization grants a damage bonus with all weapon types covered by the chosen specialization. Peasant weapons include the Hatchet, Hunting Bow, Quarterstaff, Spear and Unarmed types.',
        },
        {
            name: 'Weapon Specialization: Ruffian',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Specialization:_Ruffian',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '5',
            activation: 'Passive',
            effects: '<ul><li>Self: +15% <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a> (<a href="/wiki/Sabre" title="Sabre">Sabre</a>, <a href="/wiki/Stiletto" title="Stiletto">Stiletto</a>, <a href="/wiki/Club" title="Club">Club</a>, <a href="/wiki/Pistol" title="Pistol">Pistol</a>, <a href="/wiki/Blunderbuss" title="Blunderbuss">Blunderbuss</a>)</li></ul>',
            speed: '',
            duration: '',
            description: 'Weapon Specialization grants a damage bonus with all weapon types covered by the chosen specialization. Ruffian weapons include the Blunderbuss, Club, Pistol, Sabre, and Stiletto types.',
        },
        {
            name: 'Weapon Specialization: Soldier',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Specialization:_Soldier',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '5',
            activation: 'Passive',
            effects: '<ul><li>Self: +15% <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a> (<a href="/wiki/Great_Sword" title="Great Sword">Great Sword</a>, <a href="/wiki/Pike" title="Pike">Pike</a>, <a href="/wiki/War_Hammer" title="War Hammer">War Hammer</a>, <a href="/wiki/Arbalest" title="Arbalest">Arbalest</a>, <a href="/wiki/Arquebus" title="Arquebus">Arquebus</a>)</li></ul>',
            speed: '',
            duration: '',
            description: 'Weapon Specialization grants a damage bonus with all weapon types covered by the chosen specialization. Soldier weapons include the Arbalest, Arquebus, Great Sword, Pike, and War Hammer types.',
        },
        {
            name: 'Armored Grace',
            link: 'https://pillarsofeternity.fandom.com/wiki/Armored_Grace',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '7',
            activation: 'Passive',
            effects: '<ul><li>Self: -20% Armor Speed penalty</li></ul>',
            speed: '',
            duration: '',
            description: 'The fighter is perfectly suited to wear even bulky and restrictive suits of armor, lowering their Recovery Penalty significantly.',
        },
        {
            name: 'Clear Out',
            link: 'https://pillarsofeternity.fandom.com/wiki/Clear_Out',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/5/50/Clear_out_icon.png',
            level: '7',
            activation: 'Active',
            effects: '<ul><li>Foe AoE: 30-40 <a href="/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> damage</li><li>Foe AoE: 5.0m Push</li><li>Foe AoE: <a href="/wiki/Prone" class="mw-redirect" title="Prone">Prone</a></li></ul>',
            speed: 'Average',
            duration: '5.0 seconds',
            description: 'Sweeps the fighter\'s melee weapon in a large arc, knocking enemies Prone and causing Crush damage.',
        },
        {
            name: 'Fearless',
            link: 'https://pillarsofeternity.fandom.com/wiki/Fearless',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '7',
            activation: 'Passive',
            effects: '<ul><li>Self: Immunity: <a href="/wiki/Frightened" class="mw-redirect" title="Frightened">Frightened</a>, <a href="/wiki/Terrified" class="mw-redirect" title="Terrified">Terrified</a></li></ul>',
            speed: '',
            duration: '',
            description: 'The fighter is immune to the Frightened and Terrified afflictions.',
        },
        {
            name: 'Overbearing Guard',
            link: 'https://pillarsofeternity.fandom.com/wiki/Overbearing_Guard',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '7',
            activation: 'Passive',
            effects: '<ul><li>Target: <a href="/wiki/Prone" class="mw-redirect" title="Prone">Prone</a></li></ul>',
            speed: 'Average',
            duration: '5.0 seconds',
            description: 'The fighter\'s Disengagement Attacks have increased Accuracy, Damage, and will knock enemies Prone.',
        },
        {
            name: 'Unbending',
            link: 'https://pillarsofeternity.fandom.com/wiki/Unbending',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/7/7c/Unbending_icon.png',
            level: '7',
            activation: 'Active',
            effects: '<ul><li>User: 50% of <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a> taken converted to <a href="/wiki/Healing_Over_Time?action=edit&amp;redlink=1" class="new" title="Healing Over Time (page does not exist)">Healing Over Time</a></li></ul>',
            speed: 'Instant',
            duration: '15.0 seconds',
            description: 'The fighter draws strength from his or her own indomitable spirit, causing them to regenerate 50% of Endurance lost from an attack.',
        },
        {
            name: 'Critical Defense',
            link: 'https://pillarsofeternity.fandom.com/wiki/Critical_Defense',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/8d/Fighter_passive_icon.png',
            level: '9',
            activation: 'Passive',
            effects: '<ul><li>Self: +20% of incoming <a href="/wiki/Crit" class="mw-redirect" title="Crit">Crits</a> converted to <a href="/wiki/Hit" class="mw-redirect" title="Hit">Hits</a></li><li>Self: +10% of incoming <a href="/wiki/Hit" class="mw-redirect" title="Hit">Hits</a> converted to <a href="/wiki/Graze" class="mw-redirect" title="Graze">Grazes</a></li></ul>',
            speed: '',
            duration: '',
            description: 'The fighter expends extra effort to repel the most savage blows, causing a percentage of all incoming Critical Hits to be converted to Hits and Hits converted to Grazes.',
        },
        {
            name: 'Take the Hit',
            link: 'https://pillarsofeternity.fandom.com/wiki/Take_the_Hit',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/8/88/Take_the_hit_icon.png',
            level: '11',
            activation: 'Modal',
            effects: '<ul><li>Friendly Aura: 50% of <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a> taken redirected to Caster as <a href="/wiki/Raw" class="mw-redirect" title="Raw">Raw</a> damage</li></ul>',
            speed: 'Instant',
            duration: '',
            description: 'The fighter interposes himself or herself between incoming attacks at nearby allies. The final damage total of any attack against a nearby ally is cut in half, with the fighter taking the other half as Raw damage.',
        },
        {
            name: 'Unbroken (ability)',
            link: 'https://pillarsofeternity.fandom.com/wiki/Unbroken_(ability)',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/01/Unbroken_icon.png',
            level: '11',
            activation: 'Passive',
            effects: '<ul><li>Revive with 100 <a href="/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png" decoding="async" width="16" height="16" /></a></li><li>+5 <a href="/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a> for 30 seconds</li><li>+10 <a href="/wiki/Deflection" title="Deflection"><img alt="Deflection" src="https://static.wikia.nocookie.net/eternitywiki/images/3/3e/Deflection_icon.png" decoding="async" width="18" height="18" /></a> for 30 seconds</li><li>+10 <a href="/wiki/Fortitude" title="Fortitude"><img alt="Fortitude" src="https://static.wikia.nocookie.net/eternitywiki/images/b/b9/Fortitude_icon.png" decoding="async" width="18" height="18" /></a> for 30 seconds</li><li>+10 <a href="/wiki/Reflex" title="Reflex"><img alt="Reflex" src="https://static.wikia.nocookie.net/eternitywiki/images/8/80/Reflex_icon.png" decoding="async" width="18" height="18" /></a> for 30 seconds</li><li>+10 <a href="/wiki/Will" title="Will"><img alt="Will" src="https://static.wikia.nocookie.net/eternitywiki/images/9/96/Will_icon.png" decoding="async" width="18" height="18" /></a> for 30 seconds</li></ul>',
            speed: '',
            duration: '30.0 seconds',
            description: 'The fighter refuses to be vanquished. After being knocked out, the fighter stands back up with a portion of his or her Endurance healed and temporary bonuses to all defenses and Damage Reductions.',
        },
        {
            name: 'Charge',
            link: 'https://pillarsofeternity.fandom.com/wiki/Charge',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/1/1c/Charge_icon.png',
            level: '13',
            activation: 'Active',
            effects: '<ul><li>Foe Target: 50-65 <a href="/wiki/Crush" title="Crush"><img alt="Crush" src="https://static.wikia.nocookie.net/eternitywiki/images/8/8f/Crush_icon.png" decoding="async" width="18" height="18" /></a> <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a> on anyone in path</li></ul>',
            speed: 'Average',
            duration: '',
            description: 'The fighter dashes across the battlefield in a flash, inflicting Crush damage on anyone caught in his or her path.',
        },
        {
            name: 'Sundering Blow',
            link: 'https://pillarsofeternity.fandom.com/wiki/Sundering_Blow',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/c/cb/Sundering_blow_icon.png',
            level: '13',
            activation: 'Active',
            effects: '<ul><li>Target: -8 <a href="/wiki/Damage_Reduction" title="Damage Reduction (DR)"><img alt="Damage Reduction (DR)" src="https://static.wikia.nocookie.net/eternitywiki/images/2/29/Damage_reduction_icon.png" decoding="async" width="16" height="16" /></a></li><li>User: <a href="/wiki/Primary_Attack?action=edit&amp;redlink=1" class="new" title="Primary Attack (page does not exist)">Primary Attack</a>, +20% Melee <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a></li></ul>',
            speed: 'Average',
            duration: '8.0 seconds',
            description: 'The fighter makes a Primary attack that does additional damage and lowers the target\'s base Damage Reduction.',
        },
        {
            name: 'Triggered Immunity',
            link: 'https://pillarsofeternity.fandom.com/wiki/Triggered_Immunity',
            imageLink: 'https://static.wikia.nocookie.net/eternitywiki/images/0/06/Triggered_immunity_icon.png',
            level: '15',
            activation: 'Active',
            effects: '<ul><li>User: Immunity: <a href="/wiki/Slash" title="Slash"><img alt="Slash" src="https://static.wikia.nocookie.net/eternitywiki/images/5/50/Slash_icon.png" decoding="async" width="18" height="18" /></a> <a href="/wiki/Damage" class="mw-redirect" title="Damage">damage</a></li></ul>',
            speed: 'Instant',
            duration: '15.0 seconds',
            description: 'If the fighter is hit by damage that does at least 10% of his or her total Endurance, he or she will gain immunity to that damage type for a short duration.',
        },
    ],
    talents: [
        {
            name: 'Bonus Knock Down',
            description: 'Grants the fighter an additional use of Knock Down per encounter.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Bonus_Knock_Down',
            imageLink: fighterPassiveImageLink,
            requiredAbility: 'Knock Down'
        },
        {
            name: 'Wary Defender',
            effects: 'Increases the fighter\'s awareness while in Defender mode, granting a +5 bonus to Fortitude, Reflexes, and Will.',
            link: 'https://pillarsofeternity.fandom.com/wiki/Wary_Defender',
            imageLink: fighterPassiveImageLink,
            requiredAbility: 'Defender'
        },
        {
            name: 'Rapid Recovery',
            effects: '<ul><li>+32 <a href="/wiki/Endurance" title="Endurance"><img alt="Endurance" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e8/Endurance_icon.png/revision/latest/scale-to-width-down/16?cb=20170928235322" decoding="async" width="16" height="16"></a> over time (base)</li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Rapid_Recovery',
            imageLink: fighterPassiveImageLink
        },
        {
            name: 'Weapon Mastery: Adventurer',
            effects: '<ul><li>+10% <a href="/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235308" decoding="async" width="18" height="18"></a> with <a href="/wiki/Pollaxe" title="Pollaxe">Pollaxe</a>, <a href="/wiki/Estoc" title="Estoc">Estoc</a>, <a href="/wiki/Flail" title="Flail">Flail</a>, <a href="/wiki/Wand" title="Wand">Wand</a>,&nbsp;<a href="/wiki/War_Bow" title="War Bow">War Bow</a></li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Mastery:_Adventurer',
            imageLink: fighterPassiveImageLink,
            requiredAbility: 'Weapon Specialization: Adventurer'
        },
        {
            name: 'Weapon Mastery: Knight',
            effects: '<ul><li>+10% <a href="/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235308" decoding="async" width="18" height="18"></a> with <a href="/wiki/Battle_Axe" title="Battle Axe">Battle Axe</a>, <a href="/wiki/Sword" title="Sword">Sword</a>, <a href="/wiki/Morning_Star" title="Morning Star">Morning Star</a>, <a href="/wiki/Crossbow" title="Crossbow">Crossbow</a></li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Mastery: Knight',
            imageLink: fighterPassiveImageLink,
            requiredAbility: 'Weapon Specialization: Knight'
        },
        {
            name: 'Weapon Mastery: Noble',
            effects: '<ul><li>+10% <a href="/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235308" decoding="async" width="18" height="18"></a> with <a href="/wiki/Dagger" title="Dagger">Dagger</a>, <a href="/wiki/Rapier" title="Rapier">Rapier</a>, <a href="/wiki/Mace" title="Mace">Mace</a>, <a href="/wiki/Scepter" title="Scepter">Scepter</a>, <a href="/wiki/Rod" title="Rod">Rod</a></li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Mastery: Noble',
            imageLink: fighterPassiveImageLink,
            requiredAbility: 'Weapon Specialization: Noble'
        },
        {
            name: 'Weapon Mastery: Peasant',
            effects: '<ul><li>+10% <a href="/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235308" decoding="async" width="18" height="18"></a> with <a href="/wiki/Hatchet" title="Hatchet">Hatchet</a>, <a href="/wiki/Spear" title="Spear">Spear</a>, <a href="/wiki/Quarterstaff" title="Quarterstaff">Quarterstaff</a>, <a href="/wiki/Hunting_Bow" title="Hunting Bow">Hunting Bow</a>, <a href="/wiki/Unarmed" class="mw-redirect" title="Unarmed">Unarmed</a></li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Mastery: Peasant',
            imageLink: fighterPassiveImageLink,
            requiredAbility: 'Weapon Specialization: Peasant'
        },
        {
            name: 'Weapon Mastery: Ruffian',
            effects: '<ul><li>+10% <a href="/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235308" decoding="async" width="18" height="18"></a> with <a href="/wiki/Sabre" title="Sabre">Sabre</a>, <a href="/wiki/Stiletto" title="Stiletto">Stiletto</a>, <a href="/wiki/Club" title="Club">Club</a>, <a href="/wiki/Pistol" title="Pistol">Pistol</a>, <a href="/wiki/Blunderbuss" title="Blunderbuss">Blunderbuss</a></li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Mastery: Ruffian',
            imageLink: fighterPassiveImageLink,
            requiredAbility: 'Weapon Specialization: Ruffian'
        },
        {
            name: 'Weapon Mastery: Soldier',
            effects: '<ul><li>+10% <a href="/wiki/Damage" title="Damage"><img alt="Damage" src="https://static.wikia.nocookie.net/eternitywiki/images/e/e2/Damage_icon.png/revision/latest/scale-to-width-down/18?cb=20170928235308" decoding="async" width="18" height="18"></a> with <a href="/wiki/Great_Sword" title="Great Sword">Great Sword</a>, <a href="/wiki/Pike" title="Pike">Pike</a>, <a href="/wiki/War_Hammer" title="War Hammer">War Hammer</a>, <a href="/wiki/Arbalest" title="Arbalest">Arbalest</a>, <a href="/wiki/Arquebus" title="Arquebus">Arquebus</a></li></ul>',
            link: 'https://pillarsofeternity.fandom.com/wiki/Weapon_Mastery: Soldier',
            imageLink: fighterPassiveImageLink,
            requiredAbility: 'Weapon Specialization: Soldier'
        },
    ]
};
